-- gPhone schema — the whole thing, in dependency order.
--
-- GENERATED by `pnpm generate:sql`. Do not edit by hand: every app table comes from
-- its `defineService` declaration, which is the single source of truth. A second
-- hand-maintained copy drifts, and the column allowlist that guards SQL identifier
-- interpolation is only safe while it matches the real table.
--
-- Import this one file. The order inside it matters — foreign keys cross app
-- boundaries — and it is already correct.


-- Central moderation and accountability ledger.
--
-- Every destructive or state-changing action a player takes on their own content is
-- recorded here by `server/lib/AuditLogger.ts`: deletions, archives, leaving or being
-- removed from a conversation, and moderation. It is append-only — nothing in gPhone
-- updates or deletes a row in this table — so it stays a trustworthy record after the
-- content it refers to has been soft-deleted.
--
-- `target_table` + `target_id` point at the affected row rather than using a foreign
-- key, on purpose: the log must survive the row it describes, and it spans every app
-- table. That is also why there is no FK on those columns.
CREATE TABLE IF NOT EXISTS `gphone_audit_logs` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `action` ENUM(
        'archived',
        'unarchived',
        'deleted',
        'left',
        'removed',
        'moderated',
        'unmoderated'
    ) NOT NULL,
    `service` varchar(100) NOT NULL,
    `method` varchar(100) NOT NULL,
    `target_id` int(11) NOT NULL,
    `target_table` varchar(100) DEFAULT NULL,
    `details` text DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `citizenid` (`citizenid`),
    KEY `action` (`action`),
    KEY `service_method` (`service`, `method`),
    KEY `target` (`target_table`, `target_id`),
    -- Moderation review reads newest-first for one player.
    KEY `citizenid_created` (`citizenid`, `created_at`),
    CONSTRAINT `fk_audit_logs_citizenid` FOREIGN KEY (`citizenid`) REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;



-- Generated from the 'accounts' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_accounts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `handle` varchar(32) NOT NULL,
    `display_name` varchar(50) DEFAULT NULL,
    `avatar` varchar(255) DEFAULT NULL,
    `bio` varchar(160) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `app_handle` (`app`, `handle`),
    KEY `citizenid_app` (`citizenid`, `app`),
    CONSTRAINT `fk_accounts_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_account_follows` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `follower_account_id` int(11) NOT NULL,
    `followee_account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `follower_followee` (`follower_account_id`, `followee_account_id`),
    KEY `followee_account_id` (`followee_account_id`),
    KEY `follower_recent` (`follower_account_id`, `id`),
    CONSTRAINT `fk_gphone_account_follows_follower_account_id` FOREIGN KEY (`follower_account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_account_follows_followee_account_id` FOREIGN KEY (`followee_account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_account_blocks` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blocker_account_id` int(11) NOT NULL,
    `blocked_account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `blocker_blocked` (`blocker_account_id`, `blocked_account_id`),
    KEY `blocked_account_id` (`blocked_account_id`),
    CONSTRAINT `fk_gphone_account_blocks_blocker_account_id` FOREIGN KEY (`blocker_account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_account_blocks_blocked_account_id` FOREIGN KEY (`blocked_account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_account_reactions` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `account_id` int(11) NOT NULL,
    `target_table` varchar(64) NOT NULL,
    `target_id` int(11) NOT NULL,
    `emoji` varchar(32) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `account_target_emoji` (`account_id`, `target_table`, `target_id`, `emoji`),
    KEY `target` (`target_table`, `target_id`),
    CONSTRAINT `fk_gphone_account_reactions_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'battery' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_battery` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `level` int(11) NOT NULL DEFAULT 100,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_unique` (`citizenid`),
    CONSTRAINT `fk_battery_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'blabber_dms' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_blabber_dms` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `from_account` int(11) NOT NULL,
    `to_account` int(11) NOT NULL,
    `body` varchar(500) NOT NULL,
    `read_at` timestamp DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `from_to` (`from_account`, `to_account`),
    KEY `to_from` (`to_account`, `from_account`),
    KEY `to_unread` (`to_account`, `read_at`),
    CONSTRAINT `fk_gphone_blabber_dms_from_account` FOREIGN KEY (`from_account`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_dms_to_account` FOREIGN KEY (`to_account`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_blabber_dms_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'contacts' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_contacts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `firstname` varchar(50) NOT NULL,
    `lastname` varchar(50) DEFAULT NULL,
    `phone` varchar(20) NOT NULL,
    `email` varchar(100) DEFAULT NULL,
    `avatar` mediumblob DEFAULT NULL,
    `favorite` tinyint(1) DEFAULT 0,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `phone` (`phone`),
    KEY `citizenid_phone` (`citizenid`, `phone`),
    KEY `citizenid_favorite` (`citizenid`, `favorite`, `status`),
    CONSTRAINT `fk_contacts_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'conversations' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_messages_conversations` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `is_group` tinyint(1) NOT NULL DEFAULT 0,
    `name` varchar(50) DEFAULT NULL,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_updated` (`citizenid`, `status`, `updated_at`),
    KEY `updated_at` (`updated_at`),
    CONSTRAINT `fk_conversations_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_messages_participants` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `conversation_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `role` varchar(20) NOT NULL DEFAULT 'member',
    `status` ENUM('active', 'left', 'removed', 'moderated') NOT NULL DEFAULT 'active',
    `last_read` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `left_at` timestamp DEFAULT NULL,
    `archived_at` timestamp DEFAULT NULL,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `conversation_participant` (`conversation_id`, `citizenid`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `conversation_status` (`conversation_id`, `status`),
    KEY `participant_last_read` (`citizenid`, `last_read`),
    CONSTRAINT `fk_gphone_messages_participants_conversation_id` FOREIGN KEY (`conversation_id`)
        REFERENCES `gphone_messages_conversations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_messages_participants_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'highscores' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_highscores` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `score` int(11) NOT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_app` (`citizenid`, `app`),
    CONSTRAINT `fk_highscores_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'hodlr' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_hodlr` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `quantity` int(11) NOT NULL DEFAULT 0,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_unique` (`citizenid`),
    CONSTRAINT `fk_hodlr_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_hodlr_price_history` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `price` int(11) NOT NULL,
    `recorded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `recorded_at` (`recorded_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'mail' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_mail` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `sender` varchar(100) NOT NULL,
    `sender_address` varchar(100) DEFAULT NULL,
    `subject` varchar(255) NOT NULL,
    `content` text NOT NULL,
    `read` tinyint(1) NOT NULL DEFAULT 0,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_created` (`citizenid`, `status`, `created_at`),
    KEY `citizenid_read_status` (`citizenid`, `read`, `status`),
    CONSTRAINT `fk_mail_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'media' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_media` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `kind` ENUM('photo', 'video', 'audio', 'gif', 'sticker', 'file', 'link', 'location') NOT NULL DEFAULT 'photo',
    `data` mediumtext DEFAULT NULL,
    `url` varchar(512) DEFAULT NULL,
    `thumbnail` mediumtext DEFAULT NULL,
    `mime_type` varchar(64) DEFAULT NULL,
    `width` int(11) DEFAULT NULL,
    `height` int(11) DEFAULT NULL,
    `duration_ms` int(11) DEFAULT NULL,
    `byte_size` int(11) DEFAULT NULL,
    `alt_text` varchar(255) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_created` (`citizenid`, `status`, `created_at`),
    CONSTRAINT `fk_media_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'blabber' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_blabber` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `account_id` int(11) NOT NULL,
    `body` varchar(280) DEFAULT NULL,
    `reply_to` int(11) DEFAULT NULL,
    `mouth_of` int(11) DEFAULT NULL,
    `root_id` int(11) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `account_id` (`account_id`),
    KEY `reply_to` (`reply_to`),
    KEY `root_id` (`root_id`),
    UNIQUE KEY `account_mouth` (`account_id`, `mouth_of`),
    CONSTRAINT `fk_gphone_blabber_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_reply_to` FOREIGN KEY (`reply_to`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_mouth_of` FOREIGN KEY (`mouth_of`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_root_id` FOREIGN KEY (`root_id`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_blabber_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_blabber_ears` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `blab_account` (`blab_id`, `account_id`),
    KEY `account_id` (`account_id`),
    CONSTRAINT `fk_gphone_blabber_ears_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_ears_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `gphone_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_blabber_tags` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `tag` varchar(32) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `tag` (`tag`),
    KEY `blab_id` (`blab_id`),
    CONSTRAINT `fk_gphone_blabber_tags_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_blabber_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `media_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `blab_id` (`blab_id`),
    KEY `citizenid` (`citizenid`),
    KEY `media_id` (`media_id`),
    CONSTRAINT `fk_gphone_blabber_attachments_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `gphone_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_attachments_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_blabber_attachments_media_id` FOREIGN KEY (`media_id`)
        REFERENCES `gphone_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'marketplace' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_marketplace` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `title` varchar(100) NOT NULL,
    `price` int(11) NOT NULL,
    `description` text NOT NULL,
    `status` ENUM('active', 'sold', 'removed', 'moderated', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    CONSTRAINT `fk_marketplace_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_marketplace_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `listing_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `media_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `listing_id` (`listing_id`),
    KEY `citizenid` (`citizenid`),
    KEY `media_id` (`media_id`),
    CONSTRAINT `fk_gphone_marketplace_attachments_listing_id` FOREIGN KEY (`listing_id`)
        REFERENCES `gphone_marketplace` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_marketplace_attachments_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_marketplace_attachments_media_id` FOREIGN KEY (`media_id`)
        REFERENCES `gphone_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'messages' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_messages` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `conversation_id` int(11) NOT NULL,
    `message` text NOT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid` (`citizenid`),
    KEY `conversation_status_created` (`conversation_id`, `status`, `created_at`),
    CONSTRAINT `fk_gphone_messages_conversation_id` FOREIGN KEY (`conversation_id`)
        REFERENCES `gphone_messages_conversations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_messages_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gphone_messages_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `message_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `photo_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `message_id` (`message_id`),
    KEY `citizenid` (`citizenid`),
    KEY `photo_id` (`photo_id`),
    CONSTRAINT `fk_gphone_messages_attachments_message_id` FOREIGN KEY (`message_id`)
        REFERENCES `gphone_messages` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_messages_attachments_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE,
    CONSTRAINT `fk_gphone_messages_attachments_photo_id` FOREIGN KEY (`photo_id`)
        REFERENCES `gphone_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'notes' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_notes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `title` varchar(255) DEFAULT NULL,
    `content` text DEFAULT NULL,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_updated` (`citizenid`, `status`, `updated_at`),
    CONSTRAINT `fk_notes_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'notifications' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_notifications` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `kind` varchar(32) NOT NULL,
    `title` varchar(80) NOT NULL,
    `body` varchar(255) NOT NULL,
    `avatar` varchar(255) DEFAULT NULL,
    `deep_link` text DEFAULT NULL,
    `read_at` varchar(32) DEFAULT NULL,
    `cleared_at` varchar(32) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_cleared_id` (`citizenid`, `cleared_at`, `id`),
    KEY `citizenid_app_id` (`citizenid`, `app`, `id`),
    KEY `citizenid_read` (`citizenid`, `read_at`),
    CONSTRAINT `fk_notifications_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'reports' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_reports` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `target_table` varchar(64) NOT NULL,
    `target_id` int(11) NOT NULL,
    `category` ENUM('spam', 'harassment', 'threats', 'sexual', 'impersonation', 'other') NOT NULL DEFAULT 'other',
    `note` varchar(500) DEFAULT NULL,
    `resolution` ENUM('pending', 'actioned', 'dismissed') NOT NULL DEFAULT 'pending',
    `target_preview` varchar(300) DEFAULT NULL,
    `target_author` varchar(50) DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `resolution_created` (`resolution`, `created_at`),
    KEY `target` (`target_table`, `target_id`),
    CONSTRAINT `fk_reports_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'settings' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `gphone_settings` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `setting_key` varchar(64) NOT NULL,
    `setting_value` text DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_app_key` (`citizenid`, `app`, `setting_key`),
    CONSTRAINT `fk_settings_citizenid` FOREIGN KEY (`citizenid`)
        REFERENCES `players` (`citizenid`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Versioned schema migrations ledger.
CREATE TABLE IF NOT EXISTS `gphone_schema_migrations` (
    `id` varchar(255) NOT NULL,
    `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
