-- micaOS schema for ESX (`es_extended`) and for standalone — the whole thing, in
-- dependency order.
--
-- GENERATED by `pnpm generate:sql`. Do not edit by hand. Same declarations as
-- mica.sql, with one difference: every foreign key onto `players` is omitted,
-- because that table belongs to qb and exists on neither an ESX server nor a
-- server running micaOS with no framework at all (`mica_standalone`).
--
-- Import THIS file on es_extended or standalone, and mica.sql on qbx_core or
-- qb-core. Importing the wrong one fails at the first constraint rather than
-- silently.
--
-- The constraint carried ON DELETE CASCADE, so here a deleted character leaves its
-- rows behind. On ESX nothing cleans them up. On standalone nothing needs to: there
-- is no character table to be deleted from, and micaOS is the only record a player
-- has — which is also why the orphan sweep skips there rather than guessing.


-- SPDX-FileCopyrightText: 2025 quissicutdeus
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- Central moderation and accountability ledger.
--
-- Every destructive or state-changing action a player takes on their own content is
-- recorded here by `server/lib/AuditLogger.ts`: deletions, archives, leaving or being
-- removed from a conversation, and moderation. It is append-only — nothing in micaOS
-- updates or deletes a row in this table — so it stays a trustworthy record after the
-- content it refers to has been soft-deleted.
--
-- One action, `viewed`, is not a player acting on their own content at all: it is an
-- admin reading content somebody else reported (MICA-70). It is the one exception to
-- "state-changing" above, and it exists for the same reason the rest of this table
-- does — a read otherwise leaves nothing behind for anyone to be held accountable to.
--
-- `target_table` + `target_id` point at the affected row rather than using a foreign
-- key, on purpose: the log must survive the row it describes, and it spans every app
-- table. That is also why there is no FK on those columns.
CREATE TABLE IF NOT EXISTS `mica_audit_logs` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `action` ENUM(
        'archived',
        'unarchived',
        'deleted',
        'left',
        'removed',
        'moderated',
        'unmoderated',
        'viewed'
    ) NOT NULL,
    `service` varchar(100) NOT NULL,
    `method` varchar(100) NOT NULL,
    `target_id` int(11) NOT NULL,
    `target_table` varchar(100) DEFAULT NULL,
    `details` text DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `citizenid` (`citizenid`),
    KEY `action` (`action`),
    KEY `service_method` (`service`, `method`),
    KEY `target` (`target_table`, `target_id`),
    -- Moderation review reads newest-first for one player.
    KEY `citizenid_created` (`citizenid`, `created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;



-- Generated from the 'accounts' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_accounts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `handle` varchar(32) NOT NULL,
    `display_name` varchar(50) DEFAULT NULL,
    `avatar` varchar(255) DEFAULT NULL,
    `bio` varchar(160) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `app_handle` (`app`, `handle`),
    KEY `citizenid_app` (`citizenid`, `app`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_account_follows` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `follower_account_id` int(11) NOT NULL,
    `followee_account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `follower_followee` (`follower_account_id`, `followee_account_id`),
    KEY `followee_account_id` (`followee_account_id`),
    KEY `follower_recent` (`follower_account_id`, `id`),
    CONSTRAINT `fk_mica_account_follows_follower_account_id` FOREIGN KEY (`follower_account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_account_follows_followee_account_id` FOREIGN KEY (`followee_account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_account_blocks` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blocker_account_id` int(11) NOT NULL,
    `blocked_account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `blocker_blocked` (`blocker_account_id`, `blocked_account_id`),
    KEY `blocked_account_id` (`blocked_account_id`),
    CONSTRAINT `fk_mica_account_blocks_blocker_account_id` FOREIGN KEY (`blocker_account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_account_blocks_blocked_account_id` FOREIGN KEY (`blocked_account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_account_reactions` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `account_id` int(11) NOT NULL,
    `target_table` varchar(64) NOT NULL,
    `target_id` int(11) NOT NULL,
    `emoji` varchar(32) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `account_target_emoji` (`account_id`, `target_table`, `target_id`, `emoji`),
    KEY `target` (`target_table`, `target_id`),
    CONSTRAINT `fk_mica_account_reactions_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'battery' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_battery` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `level` int(11) NOT NULL DEFAULT 100,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `phone_id_unique` (`phone_id`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'blabber_dms' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_blabber_dms` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `from_account` int(11) NOT NULL,
    `to_account` int(11) NOT NULL,
    `body` varchar(500) NOT NULL,
    `read_at` timestamp DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `from_to` (`from_account`, `to_account`),
    KEY `to_from` (`to_account`, `from_account`),
    KEY `to_unread` (`to_account`, `read_at`),
    CONSTRAINT `fk_mica_blabber_dms_from_account` FOREIGN KEY (`from_account`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_dms_to_account` FOREIGN KEY (`to_account`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'blocklist' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_blocklist` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `number` varchar(32) NOT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `phone_number_unique` (`phone_id`, `number`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'contacts' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_contacts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `firstname` varchar(50) NOT NULL,
    `lastname` varchar(50) DEFAULT NULL,
    `phone` varchar(20) NOT NULL,
    `email` varchar(100) DEFAULT NULL,
    `avatar` mediumblob DEFAULT NULL,
    `ringtone` ENUM('classic', 'chime', 'beacon', 'pulse', 'ascent') DEFAULT NULL,
    `favorite` tinyint(1) DEFAULT 0,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `phone` (`phone`),
    KEY `citizenid_phone` (`citizenid`, `phone`),
    KEY `citizenid_favorite` (`citizenid`, `favorite`, `status`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'conversations' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_messages_conversations` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `is_group` tinyint(1) NOT NULL DEFAULT 0,
    `name` varchar(50) DEFAULT NULL,
    `participant_a` varchar(50) DEFAULT NULL,
    `participant_b` varchar(50) DEFAULT NULL,
    `pair_key` varchar(101) GENERATED ALWAYS AS (CASE WHEN `status` = 'active' THEN CONCAT(LEAST(`participant_a`, `participant_b`), '|', GREATEST(`participant_a`, `participant_b`)) ELSE NULL END) VIRTUAL,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_updated` (`citizenid`, `status`, `updated_at`),
    KEY `updated_at` (`updated_at`),
    UNIQUE KEY `pair_key_unique` (`pair_key`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_messages_participants` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `conversation_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `role` varchar(20) NOT NULL DEFAULT 'member',
    `status` ENUM('active', 'left', 'removed', 'moderated') NOT NULL DEFAULT 'active',
    `last_read` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `left_at` timestamp DEFAULT NULL,
    `archived_at` timestamp DEFAULT NULL,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    UNIQUE KEY `conversation_phone_unique` (`conversation_id`, `phone_id`),
    KEY `phone_id` (`phone_id`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `conversation_status` (`conversation_id`, `status`),
    KEY `participant_last_read` (`citizenid`, `last_read`),
    CONSTRAINT `fk_mica_messages_participants_conversation_id` FOREIGN KEY (`conversation_id`)
        REFERENCES `mica_messages_conversations` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'highscores' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_highscores` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `app` varchar(32) NOT NULL,
    `score` int(11) NOT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_app` (`citizenid`, `app`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'hodlr' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_hodlr` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `quantity` int(11) NOT NULL DEFAULT 0,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `citizenid_unique` (`citizenid`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_hodlr_price_history` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `price` int(11) NOT NULL,
    `recorded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `recorded_at` (`recorded_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'lockscreen' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_lockscreen` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `passcode_hash` varchar(64) DEFAULT NULL,
    `passcode_salt` varchar(32) DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `phone_id_unique` (`phone_id`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'mail' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_mail` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `sender` varchar(100) NOT NULL,
    `sender_address` varchar(100) DEFAULT NULL,
    `subject` varchar(255) NOT NULL,
    `content` text NOT NULL,
    `read` tinyint(1) NOT NULL DEFAULT 0,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_created` (`citizenid`, `status`, `created_at`),
    KEY `citizenid_read_status` (`citizenid`, `read`, `status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'media' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_media` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `kind` ENUM('photo', 'video', 'audio', 'gif', 'sticker', 'file', 'link', 'location') NOT NULL DEFAULT 'photo',
    `data` mediumtext DEFAULT NULL,
    `url` varchar(512) DEFAULT NULL,
    `thumbnail` mediumtext DEFAULT NULL,
    `mime_type` varchar(64) DEFAULT NULL,
    `width` int(11) DEFAULT NULL,
    `height` int(11) DEFAULT NULL,
    `duration_ms` int(11) DEFAULT NULL,
    `byte_size` int(11) DEFAULT NULL,
    `alt_text` varchar(255) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_created` (`citizenid`, `status`, `created_at`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'blabber' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_blabber` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `account_id` int(11) NOT NULL,
    `body` varchar(280) DEFAULT NULL,
    `reply_to` int(11) DEFAULT NULL,
    `mouth_of` int(11) DEFAULT NULL,
    `root_id` int(11) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `account_id` (`account_id`),
    KEY `reply_to` (`reply_to`),
    KEY `root_id` (`root_id`),
    UNIQUE KEY `account_mouth` (`account_id`, `mouth_of`),
    CONSTRAINT `fk_mica_blabber_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_reply_to` FOREIGN KEY (`reply_to`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_mouth_of` FOREIGN KEY (`mouth_of`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_root_id` FOREIGN KEY (`root_id`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_blabber_ears` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `account_id` int(11) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `blab_account` (`blab_id`, `account_id`),
    KEY `account_id` (`account_id`),
    CONSTRAINT `fk_mica_blabber_ears_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_ears_account_id` FOREIGN KEY (`account_id`)
        REFERENCES `mica_accounts` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_blabber_tags` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `tag` varchar(32) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `tag` (`tag`),
    KEY `blab_id` (`blab_id`),
    CONSTRAINT `fk_mica_blabber_tags_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_blabber_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `blab_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `media_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `blab_id` (`blab_id`),
    KEY `citizenid` (`citizenid`),
    KEY `media_id` (`media_id`),
    CONSTRAINT `fk_mica_blabber_attachments_blab_id` FOREIGN KEY (`blab_id`)
        REFERENCES `mica_blabber` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_blabber_attachments_media_id` FOREIGN KEY (`media_id`)
        REFERENCES `mica_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'marketplace' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_marketplace` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `title` varchar(100) NOT NULL,
    `price` int(11) NOT NULL,
    `description` text NOT NULL,
    `status` ENUM('active', 'sold', 'removed', 'moderated', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_marketplace_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `listing_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `media_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `listing_id` (`listing_id`),
    KEY `citizenid` (`citizenid`),
    KEY `media_id` (`media_id`),
    CONSTRAINT `fk_mica_marketplace_attachments_listing_id` FOREIGN KEY (`listing_id`)
        REFERENCES `mica_marketplace` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_marketplace_attachments_media_id` FOREIGN KEY (`media_id`)
        REFERENCES `mica_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'messages' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_messages` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `conversation_id` int(11) NOT NULL,
    `message` text NOT NULL,
    `reply_to_id` int(11) DEFAULT NULL,
    `external_sender` varchar(50) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid` (`citizenid`),
    KEY `conversation_status_created` (`conversation_id`, `status`, `created_at`),
    KEY `conversation_id_id` (`conversation_id`, `id`),
    KEY `reply_to_id` (`reply_to_id`),
    CONSTRAINT `fk_mica_messages_conversation_id` FOREIGN KEY (`conversation_id`)
        REFERENCES `mica_messages_conversations` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_messages_attachments` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `message_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `photo_id` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    KEY `message_id` (`message_id`),
    KEY `citizenid` (`citizenid`),
    KEY `photo_id` (`photo_id`),
    CONSTRAINT `fk_mica_messages_attachments_message_id` FOREIGN KEY (`message_id`)
        REFERENCES `mica_messages` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_mica_messages_attachments_photo_id` FOREIGN KEY (`photo_id`)
        REFERENCES `mica_media` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mica_messages_reactions` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `message_id` int(11) NOT NULL,
    `citizenid` varchar(50) NOT NULL,
    `emoji` varchar(32) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `message_citizen_emoji` (`message_id`, `citizenid`, `emoji`),
    KEY `message_id` (`message_id`),
    CONSTRAINT `fk_mica_messages_reactions_message_id` FOREIGN KEY (`message_id`)
        REFERENCES `mica_messages` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'notes' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_notes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `title` varchar(255) DEFAULT NULL,
    `content` text DEFAULT NULL,
    `status` ENUM('active', 'archived', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_updated` (`citizenid`, `status`, `updated_at`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'notifications' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_notifications` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `app` varchar(32) NOT NULL,
    `kind` varchar(32) NOT NULL,
    `title` varchar(80) NOT NULL,
    `body` varchar(255) NOT NULL,
    `avatar` varchar(255) DEFAULT NULL,
    `deep_link` text DEFAULT NULL,
    `read_at` varchar(32) DEFAULT NULL,
    `cleared_at` varchar(32) DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_cleared_id` (`citizenid`, `cleared_at`, `id`),
    KEY `citizenid_app_id` (`citizenid`, `app`, `id`),
    KEY `citizenid_read` (`citizenid`, `read_at`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'phone_call_log' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_phone_call_log` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `kind` ENUM('incoming', 'outgoing', 'missed') NOT NULL,
    `number` varchar(20) NOT NULL,
    `duration` int(11) NOT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `citizenid_status_created` (`citizenid`, `status`, `created_at`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'phonenumbers' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_phone_numbers` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `number` varchar(16) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `number_unique` (`number`),
    UNIQUE KEY `phone_id_unique` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'phones' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_phones` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) NOT NULL,
    `claimed` tinyint(1) NOT NULL DEFAULT 0,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `phone_id_unique` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'places' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_places` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `name` varchar(100) NOT NULL,
    `street_label` varchar(255) DEFAULT NULL,
    `x` float DEFAULT NULL,
    `y` float DEFAULT NULL,
    `z` float DEFAULT NULL,
    `status` ENUM('active', 'deleted', 'moderated') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'reports' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_reports` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `target_table` varchar(64) NOT NULL,
    `target_id` int(11) NOT NULL,
    `category` ENUM('spam', 'harassment', 'threats', 'sexual', 'impersonation', 'other') NOT NULL DEFAULT 'other',
    `note` varchar(500) DEFAULT NULL,
    `resolution` ENUM('pending', 'actioned', 'dismissed') NOT NULL DEFAULT 'pending',
    `target_preview` varchar(300) DEFAULT NULL,
    `target_author` varchar(50) DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    KEY `resolution_created` (`resolution`, `created_at`),
    KEY `target` (`target_table`, `target_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Generated from the 'settings' defineService declaration.
-- Do not edit by hand; change the declaration and regenerate.

CREATE TABLE IF NOT EXISTS `mica_settings` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `citizenid` varchar(50) NOT NULL,
    `phone_id` varchar(32) DEFAULT NULL,
    `app` varchar(32) NOT NULL,
    `setting_key` varchar(64) NOT NULL,
    `setting_value` text DEFAULT NULL,
    `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `status` (`status`),
    KEY `citizenid_status` (`citizenid`, `status`),
    UNIQUE KEY `phone_app_key` (`phone_id`, `app`, `setting_key`),
    KEY `phone_id` (`phone_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Versioned schema migrations ledger.
CREATE TABLE IF NOT EXISTS `mica_schema_migrations` (
    `id` varchar(255) NOT NULL,
    `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

INSERT IGNORE INTO `mica_schema_migrations` (`id`) VALUES
  ('0001_phone_numbers_follow_the_phone'),
  ('0002_phone_data_follows_the_phone'),
  ('0003_battery_follows_the_phone');
