// This file is auto-generated by scripts/generate-manifests.js
// Do not edit this file manually.
//
// Apps import icons from '@gphone/sdk', never by relative path: an add-on installed
// from the Store resolves the package and nothing else.
export { default as AddIcon } from '../components/icons/AddIcon.svelte';
export { default as ArchiveIcon } from '../components/icons/ArchiveIcon.svelte';
export { default as BackspaceIcon } from '../components/icons/BackspaceIcon.svelte';
export { default as CheckCircleIcon } from '../components/icons/CheckCircleIcon.svelte';
export { default as CheckIcon } from '../components/icons/CheckIcon.svelte';
export { default as ChevronLeftIcon } from '../components/icons/ChevronLeftIcon.svelte';
export { default as ChevronRightIcon } from '../components/icons/ChevronRightIcon.svelte';
export { default as CloseIcon } from '../components/icons/CloseIcon.svelte';
export { default as DocumentIcon } from '../components/icons/DocumentIcon.svelte';
export { default as EditIcon } from '../components/icons/EditIcon.svelte';
export { default as EmptyMailIcon } from '../components/icons/EmptyMailIcon.svelte';
export { default as EmptyPhotoIcon } from '../components/icons/EmptyPhotoIcon.svelte';
export { default as FlipCameraIcon } from '../components/icons/FlipCameraIcon.svelte';
export { default as KeypadIcon } from '../components/icons/KeypadIcon.svelte';
export { default as LightningWarningIcon } from '../components/icons/LightningWarningIcon.svelte';
export { default as ListBulletIcon } from '../components/icons/ListBulletIcon.svelte';
export { default as LocationIcon } from '../components/icons/LocationIcon.svelte';
export { default as MessageIcon } from '../components/icons/MessageIcon.svelte';
export { default as MessageStatusIcon } from '../components/icons/MessageStatusIcon.svelte';
export { default as MicrophoneIcon } from '../components/icons/MicrophoneIcon.svelte';
export { default as PaperclipIcon } from '../components/icons/PaperclipIcon.svelte';
export { default as PencilSquareIcon } from '../components/icons/PencilSquareIcon.svelte';
export { default as PhoneIcon } from '../components/icons/PhoneIcon.svelte';
export { default as PhotoIcon } from '../components/icons/PhotoIcon.svelte';
export { default as SearchIcon } from '../components/icons/SearchIcon.svelte';
export { default as SendIcon } from '../components/icons/SendIcon.svelte';
export { default as ShareIcon } from '../components/icons/ShareIcon.svelte';
export { default as ShareSquareIcon } from '../components/icons/ShareSquareIcon.svelte';
export { default as SignalIcon } from '../components/icons/SignalIcon.svelte';
export { default as SpeakerIcon } from '../components/icons/SpeakerIcon.svelte';
export { default as StarIcon } from '../components/icons/StarIcon.svelte';
export { default as TrashIcon } from '../components/icons/TrashIcon.svelte';
