// @vitest-environment jsdom
/**
 * MICA-176: which facet set this file's subject resolves against. A hook no longer
 * carries its facet — `src/main.ts` picks the in-process set for the shell and `bootAddOn`
 * picks the iframe twins for an add-on — so a test file, having neither entry point, says
 * which side it is standing in for. In-process, because a unit test stands in for the shell.
 */
import './host/inProcess/registerFacets';
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import * as sdkIndex from './index';
import * as sdkAddon from './addon';
import * as sdkApp from './app';
import * as sdkCore from './core';
import { SDK_CONTRACT_VERSION } from './version';

/**
 * The SDK's public surface, frozen — so a change that breaks a published add-on cannot
 * ship without somebody saying so (MICA-125).
 *
 * ## The incident this exists for
 *
 * On 2026-08-28 `sdk/ui/ReactionBar.svelte` went from `counts` / `mine` / `onreact` /
 * `onunreact` to `summary` / `ontoggle`. Every in-tree call site was updated in the same
 * commit, so `typecheck`, `test:unit` and `test:e2e` were all green — and every published
 * `core: false` add-on that drew a reaction row was broken, silently, with the CHANGELOG
 * saying "Action required: None". An audit found it. No check could have.
 *
 * The important detail is that **`ReactionBar` was exported before and after**. A gate
 * that diffs export *names* would have watched that break go past — and so would it have
 * for the other two silent breaks of the same fortnight: `Screen`'s layout contract, and
 * `'sound'` disappearing from `ALL_PERMISSIONS` while the array kept its name. Of the
 * eleven breaking SDK changes in this project's life, a name-level snapshot would have
 * caught six, and none of the three most recent.
 *
 * So this file captures four things, and only the first is a list of names:
 *
 *   1. the exported names of each entry point an app can actually name,
 *   2. the **props** of every exported Svelte component,
 *   3. the **members** of every exported string vocabulary (`ALL_PERMISSIONS`), and
 *   4. **parity between `index.ts` and `addon.ts`** — the two files `@gphone/sdk`
 *      resolves to depending on who is building. See that section for why.
 *
 * ## What counts as breaking
 *
 * Five things fail this gate, and every one of them breaks code that already exists:
 *
 *   - an export in the baseline that is gone,
 *   - a prop in the baseline that is gone (a **rename** shows up as exactly this),
 *   - a prop that had a default and no longer does — a call site that omitted it now
 *     gets `undefined` where it used to get a value,
 *   - a member dropped from an exported vocabulary, and
 *   - a name that crosses one of the two `@gphone/sdk` barrels and not the other,
 *     without being declared as a deliberate difference.
 *
 * **Additions pass, deliberately.** A new icon, a new hook, a new optional prop, a new
 * permission breaks nobody, and `icons.ts` / `kit/index.ts` / `host/index.ts` are
 * generated by `scripts/generate-barrels.js` — adding a file to a directory grows the
 * surface on its own. A gate that demanded a version bump for a new icon would be routed
 * around inside a week, and a gate somebody has switched off is a silent failure with
 * extra steps. The consequence is worth stating: a surface can still *widen* by `git add`
 * with nobody deciding it should be public. That is a review question, not a build one.
 *
 * ## What this cannot see, said plainly
 *
 * - **A layout or behavioural contract.** The two `Screen` changes of 2026-08 gave the
 *   content box a definite height and then took ownership of the app viewport. Neither
 *   touched a single export or prop, and both broke any add-on whose child used `h-full`
 *   or a bare `flex-1` — legal the day before. `utilityClasses.test.ts` enforces the new
 *   rule against **in-tree apps only**. No export list, no prop signature and no `.d.ts`
 *   would show this, and nothing in this file tries to. It is the largest gap and it is
 *   deliberate.
 * - **A prop's type.** `size: string` narrowing to `size: 'sm' | 'lg'`, or `number`
 *   becoming `string`, is a break this file is blind to. It reads names and defaults.
 * - **A prop that is newly required.** Optionality is read from whether the destructure
 *   supplies a default, because the three annotation shapes in this tree
 *   (`interface Props`, `$props<{...}>()`, an inline `: { class?: string }`) and
 *   `Button`'s `interface Props extends HTMLButtonAttributes` cannot all be read the same
 *   way. Optional-with-no-default is normal here (`Screen`'s `onback`), so treating a new
 *   no-default prop as required would fire on changes that break nothing. Rather than cry
 *   wolf, this gate does not see it.
 * - **Type-only exports, except across the two barrels.** The name list in
 *   `BASELINE_EXPORTS` is read from the real modules at runtime, which is what makes
 *   `export *` through three generated barrels work without reimplementing the resolver —
 *   but `export type { Host }` has no runtime footprint, so dropping or renaming an
 *   exported *type* passes that arm. The parity block reads both barrels statically and
 *   does see types, so a type that stops crossing into an add-on's bundle is caught even
 *   though a type deleted from both is not.
 * - **Behaviour behind a name that did not move.** A prop keeping its name and meaning
 *   something else is invisible here and always will be.
 * - **`@gphone/sdk/testing`.** Test-only, aliased for this repo's own suites and not for
 *   an add-on's bundle (`vite.addon.config.ts` does not map it), so it is not a contract
 *   with anybody outside this tree.
 *
 * A last one that is not a blind spot but is worth knowing: `defineApp` types
 * `manifest.permissions` as `AppPermission[]` and never validates it against
 * `ALL_PERMISSIONS` at runtime. That is why arm 3 exists — a shrinking vocabulary has no
 * runtime signal of its own.
 *
 * Nothing here reads git — no parent commit, no merge base, no `git status`. Those answer
 * differently on a shallow CI clone, on a clean tree and mid-rebase, so a gate built on
 * one is a gate that only runs in one place. The inputs are the live modules, the two
 * barrel sources and the frozen lists below, so a local run and a CI run see the same
 * thing or both fail.
 */

/**
 * What `BASELINE_EXPORTS` and `BASELINE_PROPS` below were captured at.
 *
 * The pin itself — `SDK_CONTRACT_VERSION` — is imported from `sdk/version.ts` above, and
 * this literal is what it is checked against. **They must stay equal**, which is the whole
 * mechanism: landing a break means bumping the exported constant *and* re-freezing the
 * baselines here in the same commit, so the break is a deliberate, reviewable line in a
 * diff rather than a silence.
 *
 * This half stays a literal in this file on purpose. It is not a second copy of the pin —
 * it is the record of what the lists underneath it were captured at, and importing it too
 * would make `has a baseline frozen at the version it is pinned to` compare a value with
 * itself and pass forever. One number is authored where an add-on can read it; the other
 * sits next to the frozen data it describes, which is what lets them disagree at all.
 *
 * The pin used to live here as well, and MICA-173 moved it: this file said outright that
 * "an add-on author cannot import this number", which made the one number in the tree with
 * real compatibility meaning unreadable by the only people who needed it. `sdk/version.ts`
 * is where it went, for the reasons written there — briefly, `MICA_VERSION` is a CalVer
 * build stamp that moves on every push, and `package.json`'s `1.0.0` is read by no code.
 */
const BASELINE_VERSION = '1';

const SDK_DIR = __dirname;

/**
 * The entry points an app can name, and what each resolves to.
 *
 * `@gphone/sdk` appears twice on purpose. In-process it is `index.ts`; inside a
 * `core: false` add-on's own bundle `vite.addon.config.ts` redirects it to `addon.ts`,
 * which is a **different and smaller** list. The add-on one is the contract that matters
 * for MICA-125 — it is what a published add-on actually compiled against — and the two
 * have already drifted once (`fade`/`fly` were on `index.ts` and missing from `addon.ts`
 * until Notes reached for them).
 */
const ENTRY_POINTS: Record<string, Record<string, unknown>> = {
  '@gphone/sdk': sdkIndex,
  '@gphone/sdk (add-on bundle)': sdkAddon,
  '@gphone/sdk/app': sdkApp,
  '@gphone/sdk/core': sdkCore
};

/** Barrels that re-export a `.svelte` default, and so decide which components are public. */
const COMPONENT_BARRELS = ['components.ts', 'icons.ts', 'core.ts'];

// ---------------------------------------------------------------------------
// Reading the live surface
// ---------------------------------------------------------------------------

/** The runtime export names of one entry point, sorted. */
const exportNames = (module: Record<string, unknown>): string[] =>
  Object.keys(module)
    .filter((name) => name !== 'default' && name !== '__esModule')
    .sort();

/**
 * Every exported component, mapped to the `.svelte` file behind it.
 *
 * Read from the barrel source rather than from the runtime module, because a compiled
 * Svelte 5 component is a plain function and is indistinguishable at runtime from the
 * dozens of exported hooks beside it. The barrels state the mapping outright, and
 * `every exported component is reachable from an entry point` below cross-checks the two
 * lists against each other so this parse cannot quietly go blind.
 */
const publicComponents = (): Record<string, string> => {
  const found: Record<string, string> = {};
  for (const barrel of COMPONENT_BARRELS) {
    const source = readFileSync(join(SDK_DIR, barrel), 'utf8');
    for (const m of source.matchAll(
      /^\s*export\s+\{\s*default\s+as\s+(\w+)\s*\}\s*from\s+'([^']+\.svelte)'/gm
    )) {
      found[m[1]] = join(SDK_DIR, m[2]);
    }
  }
  return found;
};

/** The contents of every `<script>` block in a Svelte file, run together. */
const scriptOf = (source: string): string =>
  [...source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map((m) => m[1]).join('\n');

/**
 * TypeScript with its comments removed, strings left intact.
 *
 * Needed before any brace matching: a JSDoc block above the destructure is full of braces
 * and a `//` in a default string value would otherwise eat the rest of the line.
 */
const stripComments = (source: string): string => {
  let out = '';
  let mode: 'code' | 'line' | 'block' | "'" | '"' | '`' = 'code';
  for (let i = 0; i < source.length; i++) {
    const c = source[i];
    const two = source.slice(i, i + 2);
    if (mode === 'code') {
      if (two === '//') {
        mode = 'line';
        i++;
        continue;
      }
      if (two === '/*') {
        mode = 'block';
        i++;
        continue;
      }
      if (c === "'" || c === '"' || c === '`') mode = c;
      out += c;
      continue;
    }
    if (mode === 'line') {
      if (c === '\n') {
        mode = 'code';
        out += '\n';
      }
      continue;
    }
    if (mode === 'block') {
      if (two === '*/') {
        mode = 'code';
        i++;
      }
      continue;
    }
    out += c;
    if (c === '\\') {
      out += source[i + 1] ?? '';
      i++;
      continue;
    }
    if (c === mode) mode = 'code';
  }
  return out;
};

/**
 * The text inside the `let { ... } = $props()` destructure, or `null` if there is none.
 *
 * Found by walking left from `$props` and balancing braces, which is what makes it work
 * for both shapes in this tree — `let { a }: Props = $props()` and
 * `let { a } = $props<{ a: string }>()` — without caring which one it is looking at.
 */
const propsDestructure = (script: string): string | null => {
  const call = /=\s*\$props\s*[<(]/.exec(script);
  if (!call) return null;

  let close = call.index - 1;
  while (close >= 0 && /\s/.test(script[close])) close--;
  // `let { a }: Props = $props()` puts the annotation between the brace and the `=`.
  if (script[close] !== '}') {
    const colon = script.lastIndexOf('}', close);
    if (colon === -1) return null;
    close = colon;
  }
  if (script[close] !== '}') return null;

  let depth = 0;
  for (let i = close; i >= 0; i--) {
    const c = script[i];
    if (c === '}') depth++;
    else if (c === '{') {
      depth--;
      if (depth === 0) return script.slice(i + 1, close);
    }
  }
  return null;
};

/** Split on commas that are not inside brackets or a string. */
const splitTopLevel = (body: string): string[] => {
  const parts: string[] = [];
  let depth = 0;
  let current = '';
  let quote: string | null = null;

  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (quote) {
      current += c;
      if (c === '\\') {
        current += body[i + 1] ?? '';
        i++;
      } else if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') {
      quote = c;
      current += c;
      continue;
    }
    if ('([{<'.includes(c) && c !== '<') depth++;
    else if (')]}'.includes(c)) depth--;
    else if (c === ',' && depth === 0) {
      parts.push(current);
      current = '';
      continue;
    }
    current += c;
  }
  parts.push(current);
  return parts.map((p) => p.trim()).filter((p) => p.length > 0);
};

/**
 * One destructured prop, encoded for the baseline: `name` when the component requires the
 * caller to supply it, `name?` when the destructure supplies a default, and `...` for a
 * rest element (dropping which stops arbitrary attributes being forwarded).
 *
 * The name is the **public** one — `class: className = ''` is `class?`, because `class` is
 * what a caller writes and `className` is a local variable nobody outside can see.
 */
const encodeProp = (entry: string): string => {
  if (entry.startsWith('...')) return '...';

  let depth = 0;
  let quote: string | null = null;
  let split = -1;
  for (let i = 0; i < entry.length; i++) {
    const c = entry[i];
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') {
      quote = c;
      continue;
    }
    if ('([{'.includes(c)) depth++;
    else if (')]}'.includes(c)) depth--;
    else if (
      c === '=' &&
      depth === 0 &&
      entry[i + 1] !== '=' &&
      entry[i + 1] !== '>' &&
      !['=', '!', '<', '>'].includes(entry[i - 1])
    ) {
      split = i;
      break;
    }
  }

  const head = (split === -1 ? entry : entry.slice(0, split)).trim();
  const name = head
    .split(':')[0]
    .trim()
    .replace(/^['"]|['"]$/g, '');
  return split === -1 ? name : `${name}?`;
};

/**
 * A component's props, sorted, or `null` when the file declares `$props` and this parser
 * could not read it. `null` is a failure, not an empty answer — see the guard below.
 */
const propsOf = (file: string): string[] | null => {
  const script = stripComments(scriptOf(readFileSync(file, 'utf8')));
  if (!/\$props\s*[<(]/.test(script)) return [];

  const body = propsDestructure(script);
  if (body === null) return null;
  return splitTopLevel(body).map(encodeProp).sort();
};

/** Every exported component's props, keyed by the name a caller imports. */
const liveProps = (): Record<string, string[] | null> => {
  const out: Record<string, string[] | null> = {};
  for (const [name, file] of Object.entries(publicComponents())) out[name] = propsOf(file);
  return out;
};

const liveExports = (): Record<string, string[]> =>
  Object.fromEntries(Object.entries(ENTRY_POINTS).map(([id, mod]) => [id, exportNames(mod)]));

// ---------------------------------------------------------------------------
// The frozen contract
// ---------------------------------------------------------------------------

/**
 * Exported string vocabularies, and their members.
 *
 * The third silent break shape, and the one neither an export list nor a prop list sees:
 * on 2026-08-?? `'sound'` was dropped from `ALL_PERMISSIONS`. The export was still there
 * and still an array, so nothing moved — but `AppPermission` is *derived* from that array
 * and `defineApp` never validates `manifest.permissions` against it at runtime (it types
 * the field and defaults it to `[]`, nothing more). A published bundle declaring the
 * removed name therefore keeps loading with the declaration silently ignored, which is
 * worse than a refusal: the manifest still says the app asks for it.
 *
 * Any exported array of strings is treated as a vocabulary, so a second one added later is
 * covered without touching this code.
 */
const isStringArray = (value: unknown): value is readonly string[] =>
  Array.isArray(value) && value.length > 0 && value.every((v) => typeof v === 'string');

const vocabularies = (module: Record<string, unknown>): Record<string, string[]> => {
  const out: Record<string, string[]> = {};
  for (const [name, value] of Object.entries(module)) {
    if (isStringArray(value)) out[name] = [...value].sort();
  }
  return out;
};

/**
 * The runtime export names of each entry point as of `BASELINE_VERSION`. **Frozen, and
 * not a file anybody maintains** — additions never need writing down, because they break
 * nobody. The only reason to edit this list is a removal, and editing it instead of
 * bumping `SDK_CONTRACT_VERSION` is a deliberate, reviewable lie in a diff rather than a
 * silence.
 *
 * `focusTrap` and `messageOf` (MICA-172) are the exception that proves the rule, and they
 * were written down on purpose. An addition is invisible to this gate until it is in the
 * baseline — so an export added and then removed two months later is a silent narrowing,
 * which is the one failure this whole file exists to prevent and the only one a *new*
 * export is uniquely exposed to. Recording them at the moment they were added is what makes
 * their eventual removal a reported break rather than nothing at all.
 *
 * Adding them does **not** move `SDK_CONTRACT_VERSION`, for the same reason `ALL_CAPABILITIES`
 * below does not: nothing compiled against v1 loses a name it was resolving. Bumping the pin
 * would announce a break to add-on authors that has not happened.
 */
const BASELINE_EXPORTS: Record<string, string[]> = {
  '@gphone/sdk': [
    'ALL_PERMISSIONS',
    'AddIcon',
    'AirplaneIcon',
    'AppPermissionError',
    'ArchiveIcon',
    'ArrowDownLeftIcon',
    'ArrowUpRightIcon',
    'Avatar',
    'BackspaceIcon',
    'BatteryIcon',
    'BellIcon',
    'BluetoothIcon',
    'Button',
    'CheckCircleIcon',
    'CheckIcon',
    'ChevronDownIcon',
    'ChevronLeftIcon',
    'ChevronRightIcon',
    'ClockIcon',
    'CloseIcon',
    'ConfirmDialog',
    'DocumentIcon',
    'EditIcon',
    'EmojiPicker',
    'EmptyMailIcon',
    'EmptyPhotoIcon',
    'EmptyState',
    'FlagIcon',
    'FlashlightIcon',
    'FlipCameraIcon',
    'FloatingActionButton',
    'MICA_BUILD_INFO',
    'MICA_VERSION',
    'HomeIcon',
    'KeypadIcon',
    'LightningWarningIcon',
    'LinkIcon',
    'ListBulletIcon',
    'ListItem',
    'LocationIcon',
    'MediaThumb',
    'MessageBar',
    'MessageIcon',
    'MessageStatusIcon',
    'MicrophoneIcon',
    'MoonIcon',
    'MusicNoteIcon',
    'NO_REACTIONS',
    'PaperclipIcon',
    'PauseIcon',
    'PhoneIcon',
    'PhotoIcon',
    'PhotoPickerModal',
    'PlayIcon',
    'ReactionBar',
    'RepeatIcon',
    'RepeatOneIcon',
    'ReplyIcon',
    'ReportButton',
    'ReportDialog',
    // Added at v1 rather than captured with the rest of the list (MICA-173). An addition
    // never needs writing down — the gate only reads this list for removals — but this one
    // is the pin an add-on's own compatibility check imports, so dropping it later would
    // break exactly the code this export was created to enable. Listing it is what makes
    // that a failure instead of a silent widening in the other direction.
    'SDK_CONTRACT_VERSION',
    'Screen',
    'SearchBar',
    'SearchIcon',
    'SegmentedControl',
    'SendIcon',
    'SettingsSection',
    'ShareIcon',
    'ShareSquareIcon',
    'ShuffleIcon',
    'SignalIcon',
    'Skeleton',
    'SkipNextIcon',
    'SkipPreviousIcon',
    'SpeakerIcon',
    'SpeakerOffIcon',
    'StarIcon',
    'StopIcon',
    'THUMBNAIL_MAX_DIMENSION',
    'THUMBNAIL_QUALITY',
    'TabBar',
    'ToggleSwitch',
    'TrashIcon',
    'UsersIcon',
    'appStorageBytes',
    'byNewest',
    'clearAppStorage',
    'computeThumbnailSize',
    'createCrudStore',
    'createPagedStore',
    'createReactionStore',
    'defineApp',
    'encodeCanvas',
    'fade',
    'fetchCatalog',
    'filterByQuery',
    'focusTrap',
    'fly',
    'formatCurrency',
    'formatDate',
    'formatDuration',
    'formatRelativeTime',
    'formatTime',
    'formatTimestamp',
    'getRemoteCatalogUrl',
    'getTrustedRemoteAppHosts',
    'hydrateSettings',
    'isBrowser',
    'loadImage',
    'makeThumbnail',
    'messageOf',
    'onAppForeground',
    'onAppMount',
    'onAppUnmount',
    'pendingReportCount',
    'placeholderAvatar',
    'placeholderPhoto',
    'placeholderPhotos',
    'registerPersistedRehydrate',
    'registerPersistedReset',
    'releaseCanvas',
    'renderMarkdown',
    'setRemoteCatalogUrl',
    'setTrustedRemoteAppHosts',
    'thumbnailFromImage',
    'tileFromColorClasses',
    'tokenizeRichText',
    'unreadMailCount',
    'unreadMessagesCount',
    'useAccount',
    'useAccounts',
    'useAdmin',
    'useAppAction',
    'useAppEvents',
    'useAppLevels',
    'useAppRegistry',
    'useBank',
    'useCall',
    'useCamera',
    'useClock',
    'useContacts',
    'useDeepLink',
    'useDevTools',
    'useDisplay',
    'useHighscores',
    'useKeybinds',
    'useLocation',
    'useMail',
    'useMarketplace',
    'useMedia',
    'useMessages',
    'useMusic',
    'useNavigation',
    'useNotificationSettings',
    'useNotifications',
    'usePagedList',
    'usePersisted',
    'usePhoneNotification',
    'useReport',
    'useReports',
    'useScrollDetect',
    'useService',
    'useSound',
    'useStorage',
    'useSystemHardware',
    'useTheme',
    'useTimer',
    'useWallpaper'
  ],
  '@gphone/sdk (add-on bundle)': [
    'ALL_PERMISSIONS',
    'AddIcon',
    'AirplaneIcon',
    'AppPermissionError',
    'ArchiveIcon',
    'ArrowDownLeftIcon',
    'ArrowUpRightIcon',
    'Avatar',
    'BackspaceIcon',
    'BatteryIcon',
    'BellIcon',
    'BluetoothIcon',
    'Button',
    'CheckCircleIcon',
    'CheckIcon',
    'ChevronDownIcon',
    'ChevronLeftIcon',
    'ChevronRightIcon',
    'ClockIcon',
    'CloseIcon',
    'ConfirmDialog',
    'DocumentIcon',
    'EditIcon',
    'EmojiPicker',
    'EmptyMailIcon',
    'EmptyPhotoIcon',
    'EmptyState',
    'FlagIcon',
    'FlashlightIcon',
    'FlipCameraIcon',
    'FloatingActionButton',
    'MICA_BUILD_INFO',
    'MICA_VERSION',
    'HomeIcon',
    'KeypadIcon',
    'LightningWarningIcon',
    'LinkIcon',
    'ListBulletIcon',
    'ListItem',
    'LocationIcon',
    'MediaThumb',
    'MessageBar',
    'MessageIcon',
    'MessageStatusIcon',
    'MicrophoneIcon',
    'MoonIcon',
    'MusicNoteIcon',
    'NO_REACTIONS',
    'PaperclipIcon',
    'PauseIcon',
    'PhoneIcon',
    'PhotoIcon',
    'PhotoPickerModal',
    'PlayIcon',
    'ReactionBar',
    'RepeatIcon',
    'RepeatOneIcon',
    'ReplyIcon',
    'ReportButton',
    'ReportDialog',
    // Added at v1 rather than captured with the rest of the list (MICA-173). An addition
    // never needs writing down — the gate only reads this list for removals — but this one
    // is the pin an add-on's own compatibility check imports, so dropping it later would
    // break exactly the code this export was created to enable. Listing it is what makes
    // that a failure instead of a silent widening in the other direction.
    'SDK_CONTRACT_VERSION',
    'Screen',
    'SearchBar',
    'SearchIcon',
    'SegmentedControl',
    'SendIcon',
    'SettingsSection',
    'ShareIcon',
    'ShareSquareIcon',
    'ShuffleIcon',
    'SignalIcon',
    'Skeleton',
    'SkipNextIcon',
    'SkipPreviousIcon',
    'SpeakerIcon',
    'SpeakerOffIcon',
    'StarIcon',
    'StopIcon',
    'THUMBNAIL_MAX_DIMENSION',
    'THUMBNAIL_QUALITY',
    'TabBar',
    'ToggleSwitch',
    'TrashIcon',
    'UsersIcon',
    'appStorageBytes',
    'bootAddOn',
    'byNewest',
    'clearAppStorage',
    'computeThumbnailSize',
    'createCrudStore',
    'createPagedStore',
    'createReactionStore',
    'defineApp',
    'encodeCanvas',
    'fade',
    'filterByQuery',
    'focusTrap',
    'fly',
    'formatCurrency',
    'formatDate',
    'formatDuration',
    'formatRelativeTime',
    'formatTime',
    'formatTimestamp',
    'hydrateSettings',
    'isBrowser',
    'loadImage',
    'makeThumbnail',
    'messageOf',
    'onAppForeground',
    'onAppMount',
    'onAppUnmount',
    'pendingReportCount',
    'registerPersistedRehydrate',
    'registerPersistedReset',
    'releaseCanvas',
    'renderMarkdown',
    'thumbnailFromImage',
    'tileFromColorClasses',
    'tokenizeRichText',
    'unreadMailCount',
    'unreadMessagesCount',
    'useAccount',
    'useAccounts',
    'useAdmin',
    'useAppAction',
    'useAppEvents',
    'useAppLevels',
    'useAppRegistry',
    'useBank',
    'useCall',
    'useCamera',
    'useClock',
    'useContacts',
    'useDeepLink',
    'useDevTools',
    'useDisplay',
    'useHighscores',
    'useKeybinds',
    'useLocation',
    'useMail',
    'useMarketplace',
    'useMedia',
    'useMessages',
    'useMusic',
    'useNavigation',
    'useNotificationSettings',
    'useNotifications',
    'usePagedList',
    'usePersisted',
    'usePhoneNotification',
    'useReport',
    'useReports',
    'useScrollDetect',
    'useService',
    'useSound',
    'useStorage',
    'useSystemHardware',
    'useTheme',
    'useTimer',
    'useWallpaper'
  ],
  '@gphone/sdk/app': ['defineApp', 'lazyBadge'],
  '@gphone/sdk/core': ['NowPlayingCard', 'useCaptureZoomBoost', 'useNuiBridge']
};

/**
 * The props of each exported component as of `BASELINE_VERSION`, in the encoding
 * `encodeProp` produces. Frozen on the same terms as the export list above.
 */
const BASELINE_PROPS: Record<string, string[]> = {
  AddIcon: ['class?'],
  AirplaneIcon: ['class?'],
  ArchiveIcon: ['class?'],
  ArrowDownLeftIcon: ['class?'],
  ArrowUpRightIcon: ['class?'],
  Avatar: ['bgClass?', 'initials?', 'showSilhouette?', 'size?', 'src?', 'textClass?'],
  BackspaceIcon: ['class?'],
  BatteryIcon: ['charge', 'class?'],
  BellIcon: ['class?'],
  BluetoothIcon: ['class?'],
  Button: ['...', 'children', 'class?', 'variant?'],
  CheckCircleIcon: ['class?'],
  CheckIcon: ['class?'],
  ChevronDownIcon: ['class?'],
  ChevronLeftIcon: ['class?'],
  ChevronRightIcon: ['class?'],
  ClockIcon: ['class?'],
  CloseIcon: ['class?'],
  ConfirmDialog: [
    'cancelText?',
    'confirmText?',
    'confirmVariant?',
    'isLoading?',
    'message',
    'oncancel',
    'onconfirm',
    'title'
  ],
  DocumentIcon: ['class?'],
  EditIcon: ['class?'],
  EmojiPicker: ['class?', 'onselect'],
  EmptyMailIcon: ['class?'],
  EmptyPhotoIcon: ['class?'],
  EmptyState: ['class?', 'description', 'icon', 'title'],
  FlagIcon: ['class?'],
  FlashlightIcon: ['class?'],
  FlipCameraIcon: ['class?'],
  FloatingActionButton: ['collapsed?', 'icon', 'label', 'onclick', 'raised?', 'title'],
  HomeIcon: ['class?'],
  KeypadIcon: ['class?'],
  LightningWarningIcon: ['class?'],
  LinkIcon: ['class?'],
  ListBulletIcon: ['class?'],
  ListItem: ['children', 'class?', 'onclick'],
  LocationIcon: ['class?'],
  MediaThumb: ['alt', 'class?', 'fit?', 'item', 'prefer?'],
  MessageBar: ['value'],
  MessageIcon: ['class?'],
  MessageStatusIcon: ['class?', 'status?'],
  MicrophoneIcon: ['class?'],
  MoonIcon: ['class?'],
  MusicNoteIcon: ['class?'],
  NowPlayingCard: ['compact?', 'mode?', 'music', 'onopen'],
  PaperclipIcon: ['class?'],
  PauseIcon: ['class?'],
  PhoneIcon: ['class?'],
  PhotoIcon: ['class?'],
  PhotoPickerModal: [
    'multiSelect?',
    'onclose',
    'onmultichange',
    'onselect',
    'selectedIds?',
    'showRemove?',
    'title?'
  ],
  PlayIcon: ['class?'],
  ReactionBar: ['class?', 'ontoggle', 'summary?'],
  RepeatIcon: ['class?'],
  RepeatOneIcon: ['class?'],
  ReplyIcon: ['class?'],
  ReportButton: ['class?', 'onclick', 'size?', 'subject'],
  ReportDialog: ['appId', 'onclose', 'targetId', 'targetTable'],
  Screen: ['actions', 'children', 'class?', 'onback', 'ontitleclick', 'overlay', 'title'],
  SearchBar: ['class?', 'focus?', 'focusRingClass?', 'placeholder?', 'value?'],
  SearchIcon: ['class?'],
  SegmentedControl: ['options'],
  SendIcon: ['class?'],
  SettingsSection: ['title'],
  ShareIcon: ['class?'],
  ShareSquareIcon: ['class?'],
  ShuffleIcon: ['class?'],
  SignalIcon: ['class?', 'level?'],
  Skeleton: ['count?'],
  SkipNextIcon: ['class?'],
  SkipPreviousIcon: ['class?'],
  SpeakerIcon: ['class?'],
  SpeakerOffIcon: ['class?'],
  StarIcon: ['class?', 'filled?'],
  StopIcon: ['class?'],
  TabBar: ['options'],
  ToggleSwitch: ['checked?'],
  TrashIcon: ['class?'],
  UsersIcon: ['class?']
};

/**
 * The members of each exported vocabulary as of `BASELINE_VERSION`, frozen on the same
 * terms as the two lists above: additions pass, a member that disappears does not.
 */
const BASELINE_VOCABULARIES: Record<string, string[]> = {
  /**
   * `AppCapability` is derived from this array and `AppManifest.requires` is typed by it,
   * so a member dropped here is the `'sound'` break again in a second vocabulary: a
   * published add-on declaring the removed name keeps loading, `defineApp` stops
   * recognising the declaration, and the app is either hidden on every server or shown on
   * one that cannot run it. Recorded here so that is a red suite rather than a silence.
   *
   * Adding it does not move `SDK_CONTRACT_VERSION`, and should not. This widens what the
   * gate watches; it takes nothing away from anything already compiled against v1, which
   * is the only thing the pin is there to date-stamp. Bumping it would announce a break to
   * add-on authors that has not happened.
   */
  ALL_CAPABILITIES: ['money'],
  ALL_PERMISSIONS: [
    'account',
    'admin',
    'app-events',
    'app-registry',
    'bank',
    'call',
    'camera',
    'clock',
    'contacts',
    'devtools',
    'display',
    'highscores',
    'keybinds',
    'location',
    'mail',
    'marketplace',
    'media',
    'messages',
    'music',
    'navigation',
    'notification-settings',
    'notifications',
    'reports',
    'social',
    'storage',
    'system-hardware',
    'theme',
    'wallpaper'
  ]
};

// ---------------------------------------------------------------------------
// The difference that matters
// ---------------------------------------------------------------------------

/** One way the live surface would break something already written against the baseline. */
interface Break {
  /** `'@gphone/sdk'` for an export, the component name for a prop. */
  where: string;
  what: string;
  kind:
    | 'export removed'
    | 'prop removed'
    | 'prop lost its default'
    | 'shape could not be read'
    | 'vocabulary member removed';
}

/**
 * A prop list keyed by the name a caller writes, valued by whether the component supplies
 * a default for it. Splitting the two apart is what lets the differ tell a prop that
 * vanished from one that merely stopped being optional — and keeps a prop that *gained* a
 * default from reading as a removal, which is a widening and breaks nobody.
 */
const defaults = (props: string[]): Map<string, boolean> =>
  new Map(props.map((p) => [p.replace(/\?$/, ''), p.endsWith('?')]));

/**
 * Every breaking difference between the live surface and the frozen one.
 *
 * Pure, so the probes at the bottom can drive it with input this repo does not have.
 */
interface Surface {
  exports: Record<string, string[]>;
  props: Record<string, string[]>;
  /** Optional so the probes below can name only the axis they are exercising. */
  vocabularies?: Record<string, string[]>;
}

const breakingChanges = (live: Surface, baseline: Surface): Break[] => {
  const breaks: Break[] = [];

  for (const [entry, names] of Object.entries(baseline.exports)) {
    const now = new Set(live.exports[entry] ?? []);
    for (const name of names) {
      if (!now.has(name)) breaks.push({ where: entry, what: name, kind: 'export removed' });
    }
  }

  for (const [component, props] of Object.entries(baseline.props)) {
    if (!(component in live.props)) {
      // A component that is gone entirely is already reported as a removed export; listing
      // each of its props again would bury that one line under twenty. But one that is
      // *still exported* and has no parsed shape is a different animal: the parse went
      // blind, and skipping it would leave its props unchecked without a word. That is the
      // fail-open shape AGENTS.md names, so it is reported instead.
      const stillExported = Object.values(live.exports).some((names) => names.includes(component));
      if (stillExported) {
        breaks.push({ where: component, what: 'its props', kind: 'shape could not be read' });
      }
      continue;
    }
    const now = defaults(live.props[component]);
    for (const [name, hadDefault] of defaults(props)) {
      if (!now.has(name)) {
        breaks.push({
          where: component,
          what: hadDefault ? `${name}?` : name,
          kind: 'prop removed'
        });
      } else if (hadDefault && !now.get(name)) {
        // The other direction — a prop that gains a default — widens what callers may
        // omit and breaks nobody, so it is deliberately not reported.
        breaks.push({ where: component, what: name, kind: 'prop lost its default' });
      }
    }
  }

  for (const [name, members] of Object.entries(baseline.vocabularies ?? {})) {
    // A vocabulary that vanished entirely is already an `export removed` line above.
    const now = new Set(live.vocabularies?.[name] ?? []);
    if (now.size === 0) continue;
    for (const member of members) {
      if (!now.has(member)) {
        breaks.push({ where: name, what: member, kind: 'vocabulary member removed' });
      }
    }
  }

  return breaks;
};

const describeBreak = (b: Break): string => `${b.where}: ${b.what} (${b.kind})`;

// ---------------------------------------------------------------------------
// `index.ts` against `addon.ts`
// ---------------------------------------------------------------------------

/**
 * The second half of this gate, and the half that catches a defect this repo has today.
 *
 * `@gphone/sdk` is **two files**. In-process it is `index.ts`; inside a `core: false`
 * add-on's own bundle `vite.addon.config.ts` rewrites the specifier to `addon.ts`. But
 * `tsconfig.app.json` maps it to `index.ts` for everybody, so an add-on that imports a
 * name present on `index.ts` and absent from `addon.ts` **typechecks clean and fails at
 * `vite build`** — and there is no alias for `@gphone/sdk/core` in the add-on config at
 * all. `addon.ts`'s own docblock records that this has already bitten once: "Notes
 * reaching for `fade` is what found it."
 *
 * Nothing pinned the two together. `seam.test.ts` checks `addon.ts` for shell imports and
 * never compares its export list to `index.ts`'s.
 *
 * So: every difference between them must be **declared** below. The lists are not an
 * exemption mechanism — they are the record of which differences somebody chose, so that
 * a new one reddens the build instead of waiting for an add-on author to hit it.
 */

/** `export * from '...'` specifiers in a barrel. */
const starReexports = (file: string): string[] =>
  [...readFileSync(join(SDK_DIR, file), 'utf8').matchAll(/^export \* from '([^']+)'/gm)]
    .map((m) => m[1])
    .sort();

/**
 * Named re-exports in a barrel, types included and marked.
 *
 * Static, unlike `exportNames` above, and that is the point: `export type { Host }` has no
 * runtime footprint, so a type that crosses one barrel and not the other is invisible to
 * an import. Both barrels write their type re-exports as literal `export type { ... } from`
 * lines, which is exactly what this reads.
 */
const namedReexports = (file: string): string[] => {
  const source = readFileSync(join(SDK_DIR, file), 'utf8');
  const names: string[] = [];
  for (const m of source.matchAll(/^export\s+(type\s+)?\{([^}]*)\}\s*from\s*'[^']+'/gm)) {
    const blockIsType = Boolean(m[1]);
    for (const raw of m[2].split(',')) {
      const part = raw.trim();
      if (part.length === 0) continue;
      const isType = blockIsType || part.startsWith('type ');
      const bare = part.startsWith('type ') ? part.slice(5).trim() : part;
      const name = (bare.split(' as ').pop() ?? bare).trim();
      names.push(isType ? `type ${name}` : name);
    }
  }
  return [...new Set(names)].sort();
};

/**
 * On `index.ts`, deliberately not on `addon.ts`: the shell's own controls. An add-on
 * cannot reach `shell/state/` by any route (§2.7, and `seam.test.ts` enforces it), and
 * these set the phone's trusted add-on hosts and its Store catalog — a sandboxed add-on
 * able to name its own host as trusted is the hole the sandbox exists to close.
 */
const SHELL_ONLY_BY_DESIGN = [
  'fetchCatalog',
  'getRemoteCatalogUrl',
  'getTrustedRemoteAppHosts',
  'setRemoteCatalogUrl',
  'setTrustedRemoteAppHosts',
  'type CatalogEntry'
];

/** On `addon.ts` only: the iframe entry point, which has no meaning in-process. */
const ADD_ON_ONLY_BY_DESIGN = ['bootAddOn'];

/**
 * Divergences nobody chose. **This list is a defect, not a policy** — it is written down
 * so it cannot grow in silence, and every entry is something an add-on should be able to
 * name and cannot.
 *
 * Closed by MICA-129: `placeholderAvatar` / `placeholderPhoto` / `placeholderPhotos`
 * (state-free and I/O-free, `lib/placeholderImage.ts` — `index.ts` said as much above its
 * own re-export of them) and the nineteen pure types whose **values already crossed** —
 * `createCrudStore`, `usePagedList`, `useKeybinds` and the rest were callable through
 * `addon.ts` with nothing to name what they returned — are now re-exported from `addon.ts`
 * too. Empty until the next divergence nobody meant to introduce.
 */
const KNOWN_DRIFT: string[] = [];

/** Names in `a` and not in `b`, minus the ones declared as intended. */
const undeclaredDivergence = (a: string[], b: string[], declared: string[]): string[] => {
  const other = new Set(b);
  const allowed = new Set(declared);
  return a.filter((name) => !other.has(name) && !allowed.has(name));
};

// ---------------------------------------------------------------------------

describe('the SDK public surface (MICA-125)', () => {
  const exportsNow = liveExports();
  const propsNow = liveProps();
  // Read off `@gphone/sdk`, which is the superset: every vocabulary an add-on can see is
  // re-exported there too, and the parity block below is what keeps that true.
  const vocabulariesNow = vocabularies(sdkIndex);

  describe('the gate can actually run', () => {
    // Every assertion below compares two lists. If either side comes back empty — a
    // failed import, a barrel that moved, a parser that lost sight of the destructure —
    // the comparison passes over nothing and reads as a clean bill of health. AGENTS.md
    // is explicit that a check which cannot run reads as a pass, so each input is
    // asserted to be there before anything is compared against it.

    it('imported every entry point', () => {
      expect(Object.keys(exportsNow).sort()).toEqual(Object.keys(ENTRY_POINTS).sort());
      for (const [entry, names] of Object.entries(exportsNow)) {
        expect(names.length, `${entry} exported nothing — the import failed`).toBeGreaterThan(0);
      }
    });

    it('found a surface of the size this SDK actually has', () => {
      // Floors, not exact counts: additions are allowed (see the header), so an equality
      // here would fire on every new icon. These are far enough below today's numbers to
      // be quiet, and far enough above zero that a half-resolved barrel is loud.
      expect(exportsNow['@gphone/sdk'].length).toBeGreaterThanOrEqual(150);
      expect(exportsNow['@gphone/sdk (add-on bundle)'].length).toBeGreaterThanOrEqual(150);
      expect(exportsNow['@gphone/sdk/app'].length).toBeGreaterThanOrEqual(2);
      expect(exportsNow['@gphone/sdk/core'].length).toBeGreaterThanOrEqual(3);
      expect(Object.keys(propsNow).length).toBeGreaterThanOrEqual(70);
      // `ALL_PERMISSIONS` at minimum. A zero here means the module resolved to something
      // that is not the SDK, and the vocabulary arm below would compare against nothing.
      expect(Object.keys(vocabulariesNow).length).toBeGreaterThan(0);
      expect(vocabulariesNow.ALL_PERMISSIONS?.length ?? 0).toBeGreaterThanOrEqual(25);
    });

    it('read the props of every exported component', () => {
      // `null` means the file declares `$props` and this file's parser could not find it —
      // a new destructuring style, say. Reporting that as "no props" would silently retire
      // the half of this gate that exists because of ReactionBar.
      const unreadable = Object.entries(propsNow)
        .filter(([, props]) => props === null)
        .map(([name]) => name);

      expect(
        unreadable,
        'the props parser could not read these components, so their shape is unchecked'
      ).toEqual([]);

      // And a component with no props at all is suspicious enough to name: every one in
      // this tree takes at least a `class`.
      const empty = Object.entries(propsNow)
        .filter(([, props]) => props !== null && props.length === 0)
        .map(([name]) => name);
      expect(empty, 'no props parsed — the destructure was found but read as empty').toEqual([]);
    });

    it('every exported component is reachable from an entry point', () => {
      // The component list is parsed out of the barrel source; the export lists come from
      // the real modules. Cross-checking them is what keeps the parse honest — a barrel
      // rewritten in a style the regex does not match would otherwise shrink the component
      // list to nothing without a word.
      const reachable = new Set(Object.values(exportsNow).flat());
      const orphans = Object.keys(propsNow).filter((name) => !reachable.has(name));

      expect(orphans, 'parsed out of a barrel but exported by no entry point').toEqual([]);
    });

    it('has a baseline to compare against', () => {
      // Emptied, truncated or half-deleted, the lists below would report every export as
      // unchanged and pass.
      expect(
        Object.keys(BASELINE_EXPORTS).sort(),
        'the frozen export baseline is missing an entry point — restore it rather than ' +
          'letting the gate go quiet'
      ).toEqual(Object.keys(ENTRY_POINTS).sort());
      expect(BASELINE_EXPORTS['@gphone/sdk'].length).toBeGreaterThanOrEqual(150);
      expect(BASELINE_EXPORTS['@gphone/sdk (add-on bundle)'].length).toBeGreaterThanOrEqual(150);
      expect(Object.keys(BASELINE_PROPS).length).toBeGreaterThanOrEqual(70);
      expect(Object.values(BASELINE_PROPS).flat().length).toBeGreaterThanOrEqual(100);
      expect(
        Object.keys(BASELINE_VOCABULARIES).length,
        'the frozen vocabulary baseline is missing — restore it rather than letting the ' +
          'gate go quiet'
      ).toBeGreaterThan(0);
      expect(BASELINE_VOCABULARIES.ALL_PERMISSIONS.length).toBeGreaterThanOrEqual(25);
    });
  });

  it('has a baseline frozen at the version it is pinned to', () => {
    // The two move together or not at all. Bumping the pin without re-freezing would
    // leave a stale list that agrees with nothing, and re-freezing without bumping the pin
    // would let a break through as a quiet edit.
    expect(
      BASELINE_VERSION,
      `the baseline was frozen at v${BASELINE_VERSION} but the contract is pinned to ` +
        `v${SDK_CONTRACT_VERSION} — re-capture BASELINE_EXPORTS and BASELINE_PROPS in the ` +
        'same commit that bumps the pin'
    ).toBe(SDK_CONTRACT_VERSION);
  });

  it('breaks no add-on that was written against the pinned contract', () => {
    const props = Object.fromEntries(
      Object.entries(propsNow).map(([name, list]) => [name, list ?? []])
    );
    const found = breakingChanges(
      { exports: exportsNow, props, vocabularies: vocabulariesNow },
      {
        exports: BASELINE_EXPORTS,
        props: BASELINE_PROPS,
        vocabularies: BASELINE_VOCABULARIES
      }
    ).map(describeBreak);

    expect(
      found,
      `this changes the shape of \`@gphone/sdk\` under every published \`core: false\` ` +
        `add-on, which compiled against v${SDK_CONTRACT_VERSION} and cannot be recompiled ` +
        'by you. If the change is intended: bump SDK_CONTRACT_VERSION, re-capture the two ' +
        'baselines below it in the same commit, and write the CHANGELOG entry under ' +
        '"Action required" naming what an add-on author has to change. Adding an export or ' +
        'an optional prop needs none of that and does not reach here.'
    ).toEqual([]);
  });

  describe('an add-on reaches the same names the typechecker showed it', () => {
    const indexNamed = namedReexports('index.ts');
    const addonNamed = namedReexports('addon.ts');

    it('read both barrels, so the comparison below is not vacuous', () => {
      // Either regex going blind — a barrel reformatted, a file renamed — would make every
      // difference disappear and the parity check read as a clean bill of health.
      expect(indexNamed.length, 'no named re-exports parsed out of index.ts').toBeGreaterThan(20);
      expect(addonNamed.length, 'no named re-exports parsed out of addon.ts').toBeGreaterThan(5);
    });

    it('re-exports the same barrels from both', () => {
      // `export * from './components'` and friends. A barrel dropped from one side takes
      // dozens of names with it at once, which is the loudest way this can go wrong and the
      // one a name-by-name diff would report as forty separate failures.
      const stars = starReexports('index.ts');
      expect(stars.length).toBeGreaterThan(3);
      expect(
        starReexports('addon.ts'),
        'index.ts and addon.ts re-export different barrels, so `@gphone/sdk` means two ' +
          'different things depending on who is building'
      ).toEqual(stars);
    });

    it('declares every name index.ts has and addon.ts does not', () => {
      expect(
        undeclaredDivergence(indexNamed, addonNamed, [...SHELL_ONLY_BY_DESIGN, ...KNOWN_DRIFT]),
        'this name is on `@gphone/sdk` when the typechecker resolves it and missing when a ' +
          '`core: false` add-on bundles it, so an add-on that imports it typechecks clean ' +
          'and fails at `vite build`. Add it to addon.ts, or — if it is shell-only on ' +
          'purpose — say so in SHELL_ONLY_BY_DESIGN.'
      ).toEqual([]);
    });

    it('declares every name addon.ts has and index.ts does not', () => {
      expect(
        undeclaredDivergence(addonNamed, indexNamed, ADD_ON_ONLY_BY_DESIGN),
        'this name exists only inside an add-on bundle, so nothing in this tree ever ' +
          'compiles against it and no suite covers it'
      ).toEqual([]);
    });

    it('hands an add-on the same runtime values, not just the same source lines', () => {
      // The static check above reads the two files; this one reads the two modules, so a
      // divergence arriving through an `export *` barrel — where nothing is written down in
      // either file — is caught too. Types are absent here by construction.
      const declared = [...SHELL_ONLY_BY_DESIGN, ...KNOWN_DRIFT].filter(
        (n) => !n.startsWith('type ')
      );
      expect(
        undeclaredDivergence(
          exportsNow['@gphone/sdk'],
          exportsNow['@gphone/sdk (add-on bundle)'],
          declared
        )
      ).toEqual([]);
      expect(
        undeclaredDivergence(
          exportsNow['@gphone/sdk (add-on bundle)'],
          exportsNow['@gphone/sdk'],
          ADD_ON_ONLY_BY_DESIGN
        )
      ).toEqual([]);
    });

    it('reports an undeclared divergence, rather than merely being configured', () => {
      expect(undeclaredDivergence(['a', 'b'], ['a'], [])).toEqual(['b']);
      expect(undeclaredDivergence(['a', 'b'], ['a'], ['b'])).toEqual([]);
      expect(undeclaredDivergence(['a', 'type T'], ['a'], ['type T'])).toEqual([]);
    });
  });

  /**
   * The assertions above pass over a surface that has not changed, so on a clean tree they
   * are a verified silence rather than a scan that happens to match nothing. These drive
   * the same differ with input this repo does not have — including a replay of the actual
   * ReactionBar break, which is the change that motivated the whole file.
   */
  describe('the check fires, rather than merely being configured', () => {
    const surface = (exports: Record<string, string[]>, props: Record<string, string[]> = {}) => ({
      exports,
      props
    });

    it('sees an export that is gone', () => {
      expect(
        breakingChanges(
          surface({ '@gphone/sdk': ['Button'] }),
          surface({ '@gphone/sdk': ['Button', 'ReactionBar'] })
        ).map(describeBreak)
      ).toEqual(['@gphone/sdk: ReactionBar (export removed)']);
    });

    it('lets an added export through', () => {
      expect(
        breakingChanges(
          surface({ '@gphone/sdk': ['Button', 'Skeleton'] }),
          surface({ '@gphone/sdk': ['Button'] })
        )
      ).toEqual([]);
    });

    it('replays the ReactionBar break of 2026-08-28', () => {
      // Props before: `counts`, `mine`, `onreact`, `onunreact`, `class`. After: `summary`,
      // `ontoggle`, `class`. The name `ReactionBar` is exported either way, which is
      // precisely why an export-name gate would have missed this.
      const before = { ReactionBar: ['class?', 'counts?', 'mine?', 'onreact', 'onunreact'] };
      const after = { ReactionBar: ['class?', 'ontoggle', 'summary?'] };
      const entry = { '@gphone/sdk': ['ReactionBar'] };

      expect(
        breakingChanges(surface(entry, after), surface(entry, before)).map(describeBreak)
      ).toEqual([
        'ReactionBar: counts? (prop removed)',
        'ReactionBar: mine? (prop removed)',
        'ReactionBar: onreact (prop removed)',
        'ReactionBar: onunreact (prop removed)'
      ]);
    });

    it('sees a prop that was renamed', () => {
      const entry = { '@gphone/sdk': ['Avatar'] };
      expect(
        breakingChanges(
          surface(entry, { Avatar: ['label?'] }),
          surface(entry, { Avatar: ['name?'] })
        ).map(describeBreak)
      ).toEqual(['Avatar: name? (prop removed)']);
    });

    it('sees a prop that lost its default, and says which', () => {
      const entry = { '@gphone/sdk': ['Avatar'] };
      expect(
        breakingChanges(
          surface(entry, { Avatar: ['size'] }),
          surface(entry, { Avatar: ['size?'] })
        ).map(describeBreak)
      ).toEqual(['Avatar: size (prop lost its default)']);
    });

    it('lets an added prop, and a newly optional one, through', () => {
      const entry = { '@gphone/sdk': ['Avatar'] };
      expect(
        breakingChanges(
          surface(entry, { Avatar: ['name?', 'size', 'tone'] }),
          surface(entry, { Avatar: ['name?', 'size'] })
        )
      ).toEqual([]);
      expect(
        breakingChanges(surface(entry, { Avatar: ['size?'] }), surface(entry, { Avatar: ['size'] }))
      ).toEqual([]);
    });

    it('refuses to skip a component that is still exported but no longer parses', () => {
      // The fail-open case: `publicComponents()` stops matching a barrel it used to read,
      // so twenty components drop out of the parsed set while every one of them is still
      // on `@gphone/sdk`. Skipping them the way a genuinely deleted component is skipped
      // would retire half this gate in silence.
      expect(
        breakingChanges(
          surface({ '@gphone/sdk': ['ReactionBar'] }, {}),
          surface({ '@gphone/sdk': ['ReactionBar'] }, { ReactionBar: ['ontoggle'] })
        ).map(describeBreak)
      ).toEqual(['ReactionBar: its props (shape could not be read)']);
    });

    it('sees a member dropped from an exported vocabulary', () => {
      // The `'sound'` case: `ALL_PERMISSIONS` is still exported and still an array, so
      // every name-level check is satisfied, and a published manifest declaring the
      // removed permission keeps loading with its declaration quietly ignored.
      const entry = { '@gphone/sdk': ['ALL_PERMISSIONS'] };
      expect(
        breakingChanges(
          { ...surface(entry), vocabularies: { ALL_PERMISSIONS: ['media', 'storage'] } },
          { ...surface(entry), vocabularies: { ALL_PERMISSIONS: ['media', 'sound', 'storage'] } }
        ).map(describeBreak)
      ).toEqual(['ALL_PERMISSIONS: sound (vocabulary member removed)']);
    });

    it('lets a member added to a vocabulary through', () => {
      const entry = { '@gphone/sdk': ['ALL_PERMISSIONS'] };
      expect(
        breakingChanges(
          { ...surface(entry), vocabularies: { ALL_PERMISSIONS: ['media', 'music'] } },
          { ...surface(entry), vocabularies: { ALL_PERMISSIONS: ['media'] } }
        )
      ).toEqual([]);
    });

    it('reads a vocabulary out of the real module, not just out of a literal', () => {
      // Same reason as the props probe below: the encoding the literals above are written
      // in has to be what `vocabularies()` actually produces for the live SDK.
      expect(vocabulariesNow.ALL_PERMISSIONS).toContain('media');
      expect(vocabulariesNow.ALL_PERMISSIONS).not.toContain('sound');
    });

    it('reports a deleted component once, not once per prop', () => {
      expect(
        breakingChanges(
          surface({ '@gphone/sdk': [] }),
          surface({ '@gphone/sdk': ['ReactionBar'] }, { ReactionBar: ['ontoggle', 'summary?'] })
        ).map(describeBreak)
      ).toEqual(['@gphone/sdk: ReactionBar (export removed)']);
    });

    it('reads props out of real components, so the parser is not asserted against itself', () => {
      // The differ above is driven with literals. This is the other half: the encoding
      // those literals are written in has to be what `propsOf` actually produces for a
      // file on disk, or the two halves agree with each other and with nothing else.
      //
      // Asserted as memberships rather than as whole lists, deliberately: an exact list
      // would fail every time somebody adds an optional prop, which this gate is on
      // record as allowing. What has to hold is that both encodings come out of a real
      // parse - a prop with a default, one without, and a rest element.
      expect(propsNow.ReactionBar).toContain('ontoggle'); // required: no default
      expect(propsNow.ReactionBar).toContain('class?'); // `class: className = ''`
      expect(propsNow.Screen).toContain('title');
      expect(propsNow.Button).toContain('...'); // `...rest`, forwarding attributes

      // And the encoding is well formed everywhere, so a component the parser mangles
      // into an unusable token cannot sit in the baseline looking like a checked one.
      const malformed = Object.entries(propsNow).flatMap(([component, props]) =>
        (props ?? [])
          .filter((p) => !/^(?:\.\.\.|[A-Za-z_$][\w$]*\??)$/.test(p))
          .map((p) => `${component}: ${p}`)
      );
      expect(malformed, 'the parser produced something that is not a prop name').toEqual([]);
    });
  });
});
