// This file is auto-generated by scripts/generate-manifests.js
// Do not edit this file manually.
import './AdminController';
import './BankController';
import './BatteryController';
import './CallController';
import './CameraController';
import './ContactController';
import './ConversationController';
import './FreelookController';
import './MailController';
import './MessageController';
import './NoteController';
import './PhoneAnimationController';
import './PhotoController';
import './ShellController';
