// This file is auto-generated by scripts/generate-manifests.js
// Do not edit this file manually.
import './BatteryController';
import './CallController';
import './CameraController';
import './ContactController';
import './FreelookController';
import './MailController';
import './PhoneAnimationController';
import './RelayController';
import './ShellController';
