// SPDX-FileCopyrightText: 2026 quissicutdeus
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generateIndex = (dir, mode = 'import', exclude = []) => {
  const fullDir = path.resolve(__dirname, '..', dir);

  if (!fs.existsSync(fullDir)) {
    console.warn(`Directory not found: ${fullDir}`);
    return;
  }

  // Tests are excluded, and not as a tidiness measure: this barrel is the public face of
  // the SDK, so a `useThing.test.ts` sitting next to `useThing.ts` was re-exported from
  // `@gos/sdk` and pulled vitest into the shipped bundle. The same applies to the
  // server and client barrels, which import for side effects — a test file there would
  // register its own describe blocks at runtime.
  //
  // `exclude` is a second, narrower reason: a handful of files are meant to be imported
  // by path within the repo but never re-exported through this barrel (and so never
  // through `@gos/sdk`). Named by module basename, no extension.
  const files = fs
    .readdirSync(fullDir)
    .filter(
      (file) =>
        file.endsWith('.ts') &&
        file !== 'index.ts' &&
        !file.endsWith('.test.ts') &&
        !file.endsWith('.d.ts') &&
        !exclude.includes(file.replace(/\.ts$/, ''))
    );

  const lines = files
    .map((file) => {
      const name = file.replace(/\.ts$/, '');
      return mode === 'export' ? `export * from './${name}';` : `import './${name}';`;
    })
    .join('\n');

  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
${lines}
`;

  fs.writeFileSync(path.join(fullDir, 'index.ts'), content);
  console.log(`Generated ${dir}/index.ts with ${files.length} ${mode}s.`);
};

/**
 * Re-export every icon component from the SDK.
 *
 * Generated rather than hand-written so adding an icon file is enough — a list that has
 * to be edited alongside is a list that drifts, and an icon missing from it is invisible
 * until an add-on tries to import it and cannot.
 */
const generateIconIndex = () => {
  const dir = 'sdk/icons.ts';
  const iconDir = path.resolve(__dirname, '..', 'sdk/ui/icons');

  if (!fs.existsSync(iconDir)) {
    console.warn(`Directory not found: ${iconDir}`);
    return;
  }

  const files = fs
    .readdirSync(iconDir)
    .filter((file) => file.endsWith('.svelte'))
    .toSorted();

  const lines = files
    .map((file) => {
      const name = file.replace('.svelte', '');
      return `export { default as ${name} } from './ui/icons/${file}';`;
    })
    .join('\n');

  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
//
// Apps import icons from '@gos/sdk', never by relative path: an add-on installed
// from the Store resolves the package and nothing else.
${lines}
`;

  fs.writeFileSync(path.resolve(__dirname, '..', dir), content);
  console.log(`Generated ${dir} with ${files.length} icons.`);
};

/**
 * Generate the fxmanifest.lua resource manifest.
 *
 * FXServer reads this to declare what files the resource needs, what commands it exports,
 * and which runtime configuration it requires. The `node_version '22'` directive opts into
 * Node 22 server-side instead of the default Node 16.
 *
 * This is generated rather than committed so that `node_version` stays in sync with the
 * TypeScript and esbuild targets in server/tsconfig.json and build/build-bundle.js.
 * If you raise the Node version there, update this generator to match.
 */
const generateFxManifest = () => {
  const pkgPath = path.resolve(__dirname, '..', 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  // npm allows `repository` as a plain URL string or as `{ type, url }`; the manifest
  // wants the URL either way, and an absent field must not print as 'undefined'.
  const repository =
    typeof pkg.repository === 'string' ? pkg.repository : (pkg.repository?.url ?? '');
  for (const [field, value] of Object.entries({
    author: pkg.author,
    version: pkg.version,
    license: pkg.license,
    description: pkg.description,
    repository
  })) {
    if (!value)
      throw new Error(
        `generate-barrels: package.json has no usable '${field}' for fxmanifest.lua.`
      );
  }

  const manifest = `fx_version 'cerulean'
game 'gta5'

author '${pkg.author}'
version '${pkg.version}'
license '${pkg.license}'
description '${pkg.description}'
repository '${repository}'

lua54 'yes'
node_version '22'

server_script 'dist/server/**/*.js'
client_script 'dist/client/**/*.js'

ui_page 'dist/web/index.html'

files {
  'dist/web/index.html',
  'dist/web/assets/**/*',
  'dist/web/*.svg',
  -- Add-ons are fetched at runtime by \`shell/state/registry.ts\` (\`./addons/<id>.js\`) and
  -- are not part of the hashed \`assets/\` graph, so \`assets/**/*\` never covered them. FiveM
  -- serves only what is declared here, so every add-on 404'd — blabber, hodlr, notes, snek.
  'dist/web/addons/**/*',
}
`;

  const filePath = path.resolve(__dirname, '..', 'fxmanifest.lua');
  fs.writeFileSync(filePath, manifest);
  console.log("Generated fxmanifest.lua with node_version '22'.");
};

/**
 * Collect every migration file into one ordered array.
 *
 * Not an import/export barrel like the others: a migration needs to be a member of an
 * array the runner can iterate in order, not a module the bundle merely loads for its side
 * effects. Sorted by filename, which is also apply order — every migration is named with a
 * numeric prefix for exactly this reason.
 *
 * Unlike the other barrels, a missing directory is not skipped: `server/migrations/` starts
 * genuinely empty — nothing has needed a breaking schema change yet (AGENTS.md §8, "Writing a
 * migration") — and code that imports this barrel must always find something to import, even
 * an empty array.
 */
const generateMigrationsIndex = () => {
  const dir = 'server/migrations';
  const fullDir = path.resolve(__dirname, '..', dir);
  fs.mkdirSync(fullDir, { recursive: true });

  const files = fs
    .readdirSync(fullDir)
    .filter((file) => file.endsWith('.ts') && file !== 'index.ts' && !file.endsWith('.test.ts'))
    .toSorted();

  const imports = files
    .map((file, i) => `import { migration as m${i} } from './${file.replace(/\.ts$/, '')}';`)
    .join('\n');
  const list = files.map((_, i) => `m${i}`).join(', ');

  const importsBlock = imports ? `${imports}\n\n` : '\n';
  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
${importsBlock}export const migrations = [${list}];
`;

  fs.writeFileSync(path.join(fullDir, 'index.ts'), content);
  console.log(`Generated ${dir}/index.ts with ${files.length} migration(s).`);
};

console.log('Generating barrels...');
generateIndex('client/services', 'import');
generateIndex('client/game', 'import');
generateIndex('server/services', 'import');
// MICA-195. `export` rather than `import`: a service contract is a value all three bundles
// read, not a side effect. Importing the barrel is still what populates `contractFor`'s
// registry, because evaluating a file runs its `defineContract` call.
generateIndex('shared/contracts', 'export');
// Two barrels, and the split is the point (MICA-16): `kit/` is what an add-on
// bundles and reaches nothing in the shell; `host/` is what an add-on asks the shell
// for. `sdk/seam.test.ts` keeps them apart.
// `protocol`/`current`/`guard` are the host protocol's own plumbing, not SDK surface: the
// shell and `sdk/index.ts` import them by path, and an app reaches `AppPermissionError`/
// `Host` only through `sdk/index.ts`'s own re-export (MICA-16 step 3).
generateIndex('sdk/host', 'export', ['protocol', 'current', 'guard']);
generateIndex('sdk/kit', 'export');
generateIconIndex();
generateMigrationsIndex();
generateFxManifest();
console.log('Done.');
