import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generateIndex = (dir, mode = 'import') => {
  const fullDir = path.resolve(__dirname, '..', dir);

  if (!fs.existsSync(fullDir)) {
    console.warn(`Directory not found: ${fullDir}`);
    return;
  }

  // Tests are excluded, and not as a tidiness measure: this barrel is the public face of
  // the SDK, so a `useThing.test.ts` sitting next to `useThing.ts` was re-exported from
  // `@gphone/sdk` and pulled vitest into the shipped bundle. The same applies to the
  // server and client barrels, which import for side effects — a test file there would
  // register its own describe blocks at runtime.
  const files = fs
    .readdirSync(fullDir)
    .filter(
      (file) =>
        file.endsWith('.ts') &&
        file !== 'index.ts' &&
        !file.endsWith('.test.ts') &&
        !file.endsWith('.d.ts')
    );

  const lines = files
    .map((file) => {
      const name = file.replace(/\.ts$/, '');
      return mode === 'export' ? `export * from './${name}';` : `import './${name}';`;
    })
    .join('\n');

  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
${lines}
`;

  fs.writeFileSync(path.join(fullDir, 'index.ts'), content);
  console.log(`Generated ${dir}/index.ts with ${files.length} ${mode}s.`);
};

/**
 * Re-export every icon component from the SDK.
 *
 * Generated rather than hand-written so adding an icon file is enough — a list that has
 * to be edited alongside is a list that drifts, and an icon missing from it is invisible
 * until an add-on tries to import it and cannot.
 */
const generateIconIndex = () => {
  const dir = 'web/src/sdk/icons.ts';
  const iconDir = path.resolve(__dirname, '..', 'web/src/sdk/ui/icons');

  if (!fs.existsSync(iconDir)) {
    console.warn(`Directory not found: ${iconDir}`);
    return;
  }

  const files = fs
    .readdirSync(iconDir)
    .filter((file) => file.endsWith('.svelte'))
    .sort();

  const lines = files
    .map((file) => {
      const name = file.replace('.svelte', '');
      return `export { default as ${name} } from './ui/icons/${file}';`;
    })
    .join('\n');

  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
//
// Apps import icons from '@gphone/sdk', never by relative path: an add-on installed
// from the Store resolves the package and nothing else.
${lines}
`;

  fs.writeFileSync(path.resolve(__dirname, '..', dir), content);
  console.log(`Generated ${dir} with ${files.length} icons.`);
};

/**
 * Collect every migration file into one ordered array.
 *
 * Not an import/export barrel like the others: a migration needs to be a member of an
 * array the runner can iterate in order, not a module the bundle merely loads for its side
 * effects. Sorted by filename, which is also apply order — every migration is named with a
 * numeric prefix for exactly this reason.
 *
 * Unlike the other barrels, a missing directory is not skipped: `server/migrations/` starts
 * genuinely empty (nothing has ever needed a breaking schema change yet, see
 * `docs/roadmap.md`), and code that imports this barrel must always find something to
 * import, even an empty array.
 */
const generateMigrationsIndex = () => {
  const dir = 'server/migrations';
  const fullDir = path.resolve(__dirname, '..', dir);
  fs.mkdirSync(fullDir, { recursive: true });

  const files = fs
    .readdirSync(fullDir)
    .filter((file) => file.endsWith('.ts') && file !== 'index.ts' && !file.endsWith('.test.ts'))
    .sort();

  const imports = files
    .map((file, i) => `import { migration as m${i} } from './${file.replace(/\.ts$/, '')}';`)
    .join('\n');
  const list = files.map((_, i) => `m${i}`).join(', ');

  const content = `// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
${imports}

export const migrations = [${list}];
`;

  fs.writeFileSync(path.join(fullDir, 'index.ts'), content);
  console.log(`Generated ${dir}/index.ts with ${files.length} migration(s).`);
};

console.log('Generating barrels...');
generateIndex('client/services', 'import');
generateIndex('client/game', 'import');
generateIndex('server/services', 'import');
generateIndex('web/src/sdk/hooks', 'export');
generateIconIndex();
generateMigrationsIndex();
console.log('Done.');
