// This file is auto-generated by scripts/generate-barrels.js
// Do not edit this file manually.
import { migration as m0 } from './0001_repair_conversation_participants';
import { migration as m1 } from './0002_conversations_pair_key';

export const migrations = [m0, m1];
