// This file is auto-generated by scripts/generate-manifests.js
// Do not edit this file manually.
import './AdminController';
import './BankController';
import './BatteryController';
import './CallController';
import './ContactController';
import './ConversationController';
import './MailController';
import './MessageController';
import './NoteController';
import './PhotoController';
import './ReportController';
import './SchemaController';
import './SeedController';
