/**
 * Parsers for values arriving from NUI.
 *
 * Every id in a `gphone:server:*` payload is attacker-controlled (AGENTS.md §9),
 * so it is parsed and range-checked before it reaches SQL or an authorization
 * check. Shared here so services cannot drift into subtly different rules.
 */

/**
 * The correlation id `fetchNui` sent with the request, echoed back on the reply.
 *
 * Opaque to the server — it is generated by the web and only ever passed through — so
 * it is typed as what it can be rather than as `any`.
 */
export type CallbackId = string | number;

/**
 * Coerce to a positive integer or throw. Rejects '', null, NaN, 0, negatives and
 * fractions — and rejects non-scalars up front, because `Number([7])` is `7`, so a
 * bare `Number()` coercion would quietly accept `{ id: [7] }` from a client.
 */
export function requirePositiveInt(raw: unknown, what: string): number {
  if (typeof raw !== 'number' && typeof raw !== 'string') {
    throw new Error(`A valid ${what} is required.`);
  }
  const value = Number(raw);
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error(`A valid ${what} is required.`);
  }
  return value;
}

/**
 * Pull a conversation id out of a payload. Accepts `{ conversation_id }`, `{ id }`,
 * or a bare id — the UI is not consistent about which it sends.
 */
export function conversationIdFrom(data: unknown): number {
  const raw = isRecord(data) ? (data.conversation_id ?? data.id) : data;
  return requirePositiveInt(raw, 'conversation_id');
}

/**
 * A NUI payload as something with readable fields.
 *
 * Handlers receive `unknown`, which is the honest type for a value the client chose.
 * This is the one place that turns it into something indexable, and it yields `unknown`
 * per field so reading one still forces a decision about what it is. A payload that is
 * not an object reads as empty rather than throwing — every field parser below already
 * rejects `undefined`, and a missing field and a malformed envelope deserve the same
 * message.
 */
export function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

export function fields(data: unknown): Record<string, unknown> {
  return isRecord(data) ? data : {};
}

/** A non-empty string, or undefined. Never the empty string, which reads as absent. */
export function optionalString(raw: unknown): string | undefined {
  return typeof raw === 'string' && raw.length > 0 ? raw : undefined;
}

/** `true` unless the client explicitly said `false` — the shape these flags default to. */
export function flagUnlessFalse(raw: unknown): boolean {
  return raw !== false;
}

/**
 * The page a custom action was asked for, clamped to what the service declared.
 *
 * `defineService` clamps the generic `get` inside `ServiceEndpoint`; a custom action does its own
 * paging and so has to clamp its own. This was written once inside `Blabber.ts` for `profile` and
 * `following`, and the accounts service's follower lists made it the third and fourth call site —
 * so it moves here rather than being copied again. It takes the resolved `paging` instead of
 * hardcoding the numbers, which is what stops a change to a declaration from silently missing that
 * service's custom actions.
 *
 * An over-large `limit` is clamped rather than refused (§10): the request is legitimate, only the
 * number is not. The cursor is a bare row id and never a column — the sort order comes from the
 * query, so a payload offering one is ignored rather than honoured.
 *
 * `ServiceEndpoint` keeps its own private pair on the generic path deliberately, because its cursor
 * error names the service it was asked of; the numbers still come from one declaration either way.
 */
export function pageBounds(
  data: unknown,
  paging: { pageSize: number; maxPageSize: number }
): { limit: number; cursor: number | null } {
  const body = fields(data);
  const rawLimit = body.limit;
  return {
    limit:
      typeof rawLimit === 'number' && Number.isInteger(rawLimit) && rawLimit > 0
        ? Math.min(rawLimit, paging.maxPageSize)
        : paging.pageSize,
    cursor:
      body.cursor === undefined || body.cursor === null
        ? null
        : requirePositiveInt(body.cursor, 'cursor')
  };
}
