// SPDX-FileCopyrightText: 2026 quissicutdeus
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * What is left of the hand-written NUI parsers.
 *
 * This file was where a service went to read a payload: `fields` to make one indexable,
 * `optionalString` and `requirePositiveInt` to pull a value out of it, one call per field per
 * handler. `shared/schema.ts` does that from a declaration now, so what remains is the part a
 * schema genuinely cannot express.
 *
 * - `requirePositiveInt` still parses an id a **handler** produced rather than one a payload
 *   carried — a value read off a row, or one an ownership check is about to discard. Its
 *   reasoning about `Number([7])` moved into the DSL's own tests, where the ninety-seven
 *   handlers that used to repeat it now inherit it.
 * - `conversationIdFrom` answers "which of two spellings arrived", which is a rule about a
 *   payload as a whole rather than about a field.
 * - `flagUnlessFalse` is a default, not a check: absent means true.
 * - `pageBounds` **clamps** rather than refuses, which is the one place this file deliberately
 *   disagrees with the schema's instinct — see its own note.
 * - `fields` survives for the two raw `onNet` handlers that never pass through
 *   `ServiceEndpoint` and so have no contract in front of them.
 *
 * Every id in a `gphone:server:*` payload is still attacker-controlled (AGENTS.md §2.9); what
 * changed is where that is written down.
 */
import { PlayerFacingError } from './errors';

/**
 * The correlation id `fetchNui` sent with the request, echoed back on the reply.
 *
 * Opaque to the server — it is generated by the web and only ever passed through — so
 * it is typed as what it can be rather than as `any`.
 */
export type CallbackId = string | number;

/**
 * The things a handler asks `requirePositiveInt` for, by name.
 *
 * A **key into the catalog**, not a word to interpolate (MICA-217). The refusal used to be
 * one sentence, `A valid {what} is required.`, with an English noun dropped into it — so a
 * German phone read „Ein gültiger Wert für ‚photo id' ist erforderlich", translated around a
 * word it could not translate. One entry per noun puts the whole sentence in the catalog,
 * and the union is what stops a caller inventing a noun the catalog has no entry for: a new
 * one is a new member here, a new `REQUIRED` line, and a new line in `server.en.json`,
 * and `serverMessages.test.ts` refuses the second without the third.
 */
export type PayloadNoun =
  'id' | 'cursor' | 'conversation' | 'photo' | 'account' | 'blab' | 'replyTarget' | 'mouthTarget';

/**
 * One literal site per noun, rather than a key built from a template, because the scanner
 * that holds every `PlayerFacingError` to the catalog reads the key as a string literal —
 * a computed one would count as keyless, and this file has no keyless baseline to hide in.
 */
const REQUIRED: Readonly<Record<PayloadNoun, () => PlayerFacingError>> = {
  id: () =>
    new PlayerFacingError('A valid numeric id is required.', {
      key: 'server.payload.required.id'
    }),
  cursor: () =>
    new PlayerFacingError('A valid cursor is required.', {
      key: 'server.payload.required.cursor'
    }),
  conversation: () =>
    new PlayerFacingError('A valid conversation id is required.', {
      key: 'server.payload.required.conversation'
    }),
  photo: () =>
    new PlayerFacingError('A valid photo id is required.', {
      key: 'server.payload.required.photo'
    }),
  account: () =>
    new PlayerFacingError('A valid account id is required.', {
      key: 'server.payload.required.account'
    }),
  blab: () =>
    new PlayerFacingError('A valid Blab id is required.', {
      key: 'server.payload.required.blab'
    }),
  replyTarget: () =>
    new PlayerFacingError('A valid reply target is required.', {
      key: 'server.payload.required.replyTarget'
    }),
  mouthTarget: () =>
    new PlayerFacingError('A valid mouth target is required.', {
      key: 'server.payload.required.mouthTarget'
    })
};

/**
 * Coerce to a positive integer or throw. Rejects '', null, NaN, 0, negatives and
 * fractions — and rejects non-scalars up front, because `Number([7])` is `7`, so a
 * bare `Number()` coercion would quietly accept `{ id: [7] }` from a client.
 */
export function requirePositiveInt(raw: unknown, what: PayloadNoun): number {
  if (typeof raw !== 'number' && typeof raw !== 'string') throw REQUIRED[what]();
  const value = Number(raw);
  if (!Number.isInteger(value) || value <= 0) throw REQUIRED[what]();
  return value;
}

/**
 * Pull a conversation id out of a payload. Accepts `{ conversation_id }`, `{ id }`,
 * or a bare id — the UI is not consistent about which it sends.
 */
export function conversationIdFrom(data: unknown): number {
  const raw = isRecord(data) ? (data.conversation_id ?? data.id) : data;
  return requirePositiveInt(raw, 'conversation');
}

/**
 * A NUI payload as something with readable fields.
 *
 * For a raw `onNet` handler, which receives `unknown` and has no contract in front of it —
 * `contacts:share` is the one that still reads a whole object this way. A payload that is not
 * an object reads as empty rather than throwing, because a missing field and a malformed
 * envelope deserve the same answer.
 */
function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

export function fields(data: unknown): Record<string, unknown> {
  return isRecord(data) ? data : {};
}

/** `true` unless the client explicitly said `false` — the shape these flags default to. */
export function flagUnlessFalse(raw: unknown): boolean {
  return raw !== false;
}

/**
 * The page a custom action was asked for, clamped to what the service declared.
 *
 * `defineService` clamps the generic `get` inside `ServiceEndpoint`; a custom action does its own
 * paging and so has to clamp its own. This was written once inside `Blabber.ts` for `profile` and
 * `following`, and the accounts service's follower lists made it the third and fourth call site —
 * so it moves here rather than being copied again. It takes the resolved `paging` instead of
 * hardcoding the numbers, which is what stops a change to a declaration from silently missing that
 * service's custom actions.
 *
 * An over-large `limit` is clamped rather than refused (§10): the request is legitimate, only the
 * number is not. The cursor is never a column — the sort order comes from the query, so a payload
 * offering one is ignored rather than honored. It defaults to a bare row id, which is what every
 * `id DESC` list pages by; `parseCursor` is how a list ordered by something else says so, and the
 * inbox passes `recencyCursor` because it sorts by last-message time (MICA-211). Widening the
 * parser rather than teaching this function a second cursor shape keeps the clamp, the default and
 * the null handling in one place for both.
 *
 * `ServiceEndpoint` keeps its own private pair on the generic path deliberately, because its cursor
 * error names the service it was asked of; the numbers still come from one declaration either way.
 */
export function pageBounds<C = number>(
  data: unknown,
  paging: { pageSize: number; maxPageSize: number },
  parseCursor: (raw: unknown) => C = ((raw: unknown) =>
    requirePositiveInt(raw, 'cursor')) as unknown as (raw: unknown) => C
): { limit: number; cursor: C | null } {
  const body = fields(data);
  const rawLimit = body.limit;
  return {
    limit:
      typeof rawLimit === 'number' && Number.isInteger(rawLimit) && rawLimit > 0
        ? Math.min(rawLimit, paging.maxPageSize)
        : paging.pageSize,
    cursor: body.cursor === undefined || body.cursor === null ? null : parseCursor(body.cursor)
  };
}

/**
 * A keyset cursor over a list ordered by *time first, id second*.
 *
 * The inbox is the one paged read whose order is not `id DESC` (MICA-211): threads sort by
 * recency of their last message, and an old thread somebody still texts daily has a low id and
 * a recent timestamp. A bare row id cannot name a position in that order at all, and the id
 * alone is not enough even alongside the time — two threads can share a timestamp to the
 * second, so the id is the tiebreak that makes the position total and the page boundary exact
 * rather than approximately right.
 *
 * `time` is a MySQL datetime string rather than a number because that is what the column
 * holds, so a bound parameter compares against it with no conversion on either side. It is
 * validated here rather than merely typed: a cursor is client-supplied like every other field
 * (§2.9). It is bound and never interpolated, so this is about refusing nonsense early rather
 * than about SQL safety — and about a bound, never authorization, which the query's own
 * citizenid join supplies.
 */
export type RecencyCursor = { time: string; id: number };

/** `YYYY-MM-DD HH:MM:SS`, the shape a `timestamp` column round-trips as. `T` accepted too. */
const SQL_DATETIME = /^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}$/;

/**
 * Whatever the driver handed back for a timestamp, as the string a cursor can carry.
 *
 * oxmysql answers a `timestamp` as a string on some builds and as a `Date` on others, and a
 * cursor has to be one thing on the wire. Anything this cannot read answers `null`, which the
 * caller turns into "no further page": a list that stops one page early is visible and
 * reportable, where a malformed cursor echoed back is a boundary that never advances and a
 * "load more" that returns the same page forever.
 */
export function toSqlDateTime(raw: unknown): string | null {
  if (raw instanceof Date) {
    return Number.isNaN(raw.getTime()) ? null : raw.toISOString().slice(0, 19).replace('T', ' ');
  }
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim().slice(0, 19);
  return SQL_DATETIME.test(trimmed) ? trimmed.replace('T', ' ') : null;
}

/** A `RecencyCursor` out of a payload, or a refusal. Both halves are required. */
export function recencyCursor(raw: unknown): RecencyCursor {
  const body = fields(raw);
  const time = toSqlDateTime(body.time);
  if (time === null) throw REQUIRED.cursor();
  return { time, id: requirePositiveInt(body.id, 'cursor') };
}
