name: Build Test
on: [push, pull_request]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
        pnpm-version: [10]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        name: Install pnpm ${{ matrix.pnpm-version }}
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies NUI
        run: pnpm install --frozen-lockfile
      - name: Run Unit Tests
        run: pnpm test:unit
      - name: Build Bundles
        run: pnpm build
